// apps/frontend/src/lib/featureFlags.ts
export const FEATURE_FLAGS = {
    FEEDBACK_WIDGET: process.env.NEXT_PUBLIC_FEATURE_FEEDBACK_WIDGET === 'true',
    VALUE_ESTIMATOR: process.env.NEXT_PUBLIC_FEATURE_VALUE_ESTIMATOR === 'true',
    BUDGET_TRACKER: process.env.NEXT_PUBLIC_FEATURE_BUDGET_TRACKER === 'true',
    MILESTONE_CELEBRATIONS: process.env.NEXT_PUBLIC_FEATURE_MILESTONE_CELEBRATIONS === 'true',
    PROPERTY_NARRATIVE_ENGINE: process.env.NEXT_PUBLIC_FEATURE_PROPERTY_NARRATIVE_ENGINE !== 'false',
    HOME_HABIT_COACH: process.env.NEXT_PUBLIC_FEATURE_HOME_HABIT_COACH !== 'false',
    MORTGAGE_REFINANCE_RADAR: process.env.NEXT_PUBLIC_FEATURE_MORTGAGE_REFINANCE_RADAR !== 'false',
  } as const;
