apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: admin-tools
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: "admin@example.com"
  PGADMIN_DEFAULT_PASSWORD: "AdminPassword123!"
