import {
  ShieldCheck,
  Hammer,
  BarChart2,
  BookOpen,
  Cpu,
  Sparkles,
  UserCog,
  ScrollText,
  Star,
  Briefcase,
  CalendarClock,
  FolderKanban,
  Inbox,
  CreditCard,
  ShieldQuestion,
  BookCheck,
} from 'lucide-react';
import type { NavJob } from './jobsNavigation';

/**
 * Dedicated admin console nav. Renders in place of PRIMARY_JOBS for the
 * ADMIN role (see getNavSectionsForRole in jobsNavigation.ts) — never
 * appended alongside the homeowner nav. Keys are `admin-*`-prefixed so
 * they can never collide with PRIMARY_JOBS' 'fix'/'home-lab' keys, which
 * the nav components special-case outside their generic render loop.
 */
export const ADMIN_NAV: NavJob[] = [
  {
    key: 'admin-work-queues',
    name: 'Work Queues',
    href: '/dashboard/admin/work-queues',
    icon: Inbox,
    description: 'Every actionable admin queue at a glance',
    engines: [],
    globalHref: true,
  },
  {
    key: 'admin-provider-compliance',
    name: 'Provider Compliance',
    href: '/dashboard/admin/provider-compliance',
    icon: ShieldCheck,
    description: 'Review provider credentials and compliance',
    engines: [],
    globalHref: true,
  },
  {
    key: 'admin-diy-templates',
    name: 'DIY Templates',
    href: '/dashboard/admin/diy/templates',
    icon: Hammer,
    description: 'Manage DIY project templates',
    engines: [],
    globalHref: true,
  },
  {
    key: 'admin-analytics',
    name: 'Analytics',
    href: '/dashboard/analytics-admin',
    icon: BarChart2,
    description: 'Product analytics dashboard',
    engines: [],
    globalHref: true,
  },
  {
    key: 'admin-content-reviews',
    name: 'Pending Reviews',
    href: '/dashboard/admin/content-reviews',
    icon: BookCheck,
    description: 'Editorial queues: review decisions and publication',
    engines: [],
    globalHref: true,
  },
  {
    key: 'admin-knowledge',
    name: 'Knowledge Admin',
    href: '/dashboard/knowledge-admin',
    icon: BookOpen,
    description: 'Manage Knowledge Hub articles',
    engines: [],
    globalHref: true,
  },
  {
    key: 'admin-worker-jobs',
    name: 'Worker Jobs',
    href: '/dashboard/worker-jobs',
    icon: Cpu,
    description: 'Background job registry',
    engines: [],
    globalHref: true,
  },
  {
    key: 'admin-user-support',
    name: 'User & Account Support',
    href: '/dashboard/admin/users',
    icon: UserCog,
    description: 'Search accounts, revoke sessions, change account status',
    engines: [],
    globalHref: true,
  },
  {
    key: 'admin-provider-ops',
    name: 'Provider Operations',
    href: '/dashboard/admin/providers',
    icon: Briefcase,
    description: 'Provider directory, credentials, and marketplace actions',
    engines: [],
    globalHref: true,
  },
  {
    key: 'admin-booking-ops',
    name: 'Booking Operations',
    href: '/dashboard/admin/bookings',
    icon: CalendarClock,
    description: 'Search bookings and trace operational timelines',
    engines: [],
    globalHref: true,
  },
  {
    key: 'admin-cases',
    name: 'Cases',
    href: '/dashboard/admin/cases',
    icon: FolderKanban,
    description: 'Safety, abuse, dispute, and support case management',
    engines: [],
    globalHref: true,
  },
  {
    key: 'admin-payment-ops',
    name: 'Payment Operations',
    href: '/dashboard/admin/payments',
    icon: CreditCard,
    description: 'Payment ledger and two-person refund decisions',
    engines: [],
    globalHref: true,
  },
  {
    key: 'admin-privacy-requests',
    name: 'Privacy Requests',
    href: '/dashboard/admin/privacy',
    icon: ShieldQuestion,
    description: 'Subject-rights request intake and tracking',
    engines: [],
    globalHref: true,
  },
  {
    key: 'admin-review-moderation',
    name: 'Review Moderation',
    href: '/dashboard/admin/reviews',
    icon: Star,
    description: 'Approve, reject, flag, or restore provider reviews',
    engines: [],
    globalHref: true,
  },
  {
    key: 'admin-audit-explorer',
    name: 'Audit Explorer',
    href: '/dashboard/admin/audit',
    icon: ScrollText,
    description: 'Trace admin actions by actor, entity, or request',
    engines: [],
    globalHref: true,
  },
  {
    key: 'admin-personalization',
    name: 'Personalization',
    href: '/dashboard/admin/personalization',
    icon: Sparkles,
    description: 'Review and activate personalization catalog versions',
    engines: [],
    globalHref: true,
  },
];
