// Ask orchestrator facade. The orchestrator used to be one 20,000-line file; its code now lives in:
//   handlers/*.handler.ts      one file per capability family (reads, propose and confirm flows); each registers itself
//   execution/*.ts             the execution lifecycle: dispatch, create, capture, clarification, confirm, sessions, feedback, concierge
//   askHandlerSupport.ts       helpers shared by the handlers and the lifecycle
//   askFormatting.ts           small display formatters
// This file imports them (so the handlers register before anything is dispatched) and re-exports every name the
// orchestrator used to export, so existing imports keep working. See
// docs/architecture/ASK_ORCHESTRATOR_DECOMPOSITION_REVIEW.md. Do not add logic here.
import './handlers/statusBoard.handler';
export { EVIDENCE_ATTACH_MESSAGE, EVIDENCE_ATTACH_MESSAGES } from './handlers/miscHandlers.handler';
import './execution/createAskExecution';
export { createAskExecution } from './execution/createAskExecution';
import './execution/askClarification';
export { submitAskClarification, resolveAskExecutionProperty } from './execution/askClarification';
import './execution/askConfirm';
export { confirmAskExecution, editAskConfirmation, cancelAskExecution } from './execution/askConfirm';
import './execution/askCapture';
export { submitAskCapture, recordAskCaptureEvent, recordAskCaptureFailure } from './execution/askCapture';
import './execution/askFeedback';
export { requestAskCorrection, submitAskExecutionFeedback, submitHomeActionUsefulnessFeedback } from './execution/askFeedback';
import './execution/askSessions';
export { getAskSession, getRecentAskSessions, updateAskSessionForUser, getAskExecution, getAskPendingWork, continueAskExecution } from './execution/askSessions';
import './execution/askConcierge';
export { getConciergeHome } from './execution/askConcierge';
import './handlers/miscHandlers.handler';
export { operationalWorkCompletionObservedResult } from './handlers/miscHandlers.handler';
import './handlers/captureConfirm.handler';
import './handlers/workflowConfirm.handler';
export { saleReadinessItemConflictDescription, editInspectionFindingResolveConfirmation } from './handlers/workflowConfirm.handler';
import './handlers/recordConfirm.handler';
import './handlers/hvacConfirm.handler';
import './handlers/buyerConfirm.handler';
import './handlers/maintenanceConfirm.handler';
import './handlers/radarConfirm.handler';
export { editHomeEventRadarFeedbackConfirmation } from './handlers/radarConfirm.handler';
export { HOME_EVENT_VISIBILITY_MESSAGE, InspectionResolutionSchema, isCapitalTimelineAnalysisStale, isValidDateEditInput, parseCapitalTimelineHorizonRequest, preservedExecutionHistory } from './askHandlerSupport';
import './handlers/homeActions.handler';
import './handlers/propertySummary.handler';
import './handlers/capitalPlanning.handler';
import './handlers/inspection.handler';
import './handlers/documents.handler';
import './handlers/quotes.handler';
import './handlers/refinance.handler';
import './handlers/homeRecordWrites.handler';
import './handlers/sellHoldRent.handler';
import './handlers/inventory.handler';
import './handlers/savingsOwnership.handler';
import './handlers/coverage.handler';
import './handlers/claims.handler';
import './handlers/homeEventRadar.handler';
import './handlers/hvacDecision.handler';
import './execution/executeOperation';
import './handlers/buyerPlan.handler';
import './handlers/maintenance.handler';
import './handlers/hoaCompliance.handler';
import './handlers/guidanceOverview.handler';
import './handlers/propertyBrief.handler';
import './handlers/homeTimeline.handler';
import './handlers/materialSpecs.handler';
import './handlers/applianceOracleBudget.handler';
import './handlers/doNothingSimulator.handler';
import './handlers/priceFinalization.handler';
import './handlers/negotiationShield.handler';
import './handlers/homeUpgradePlanner.handler';
import './handlers/diyProjectCenter.handler';
import './handlers/projectTracker.handler';
import './handlers/servicePriceRadar.handler';
import './handlers/aroundYourHome.handler';
import './handlers/homeRiskReplay.handler';
import './handlers/homeHabitCoach.handler';
import './handlers/homeDigitalWill.handler';
import './handlers/plantAdvisor.handler';
export { executeOperationCore, executeOperation, refreshAskExecutionAfterConflict, refreshAskSourceExecution, ASK_MUTATION_IMPACT_MAP, siblingOperationIdsForBuyerTaskMutation, selectSiblingRefreshTargets, capReconciledChildExecutions, reconcileAskExecutionSideEffects } from './execution/executeOperation';
export { oracleApplianceLabel, oracleLifespanItem, applianceFailureRiskFromView, maintenanceBudgetFromView } from './handlers/applianceOracleBudget.handler';
export { neighborhoodChangeFeedFromView } from './handlers/aroundYourHome.handler';
export { buyerTaskConflictDescription, buyerFindingConflictDescription, buyerPlanHref, buyerJourneyStageLabel, parseBuyerDeadlineLaneFilter, selectBuyerDeadlineMilestones, buildBuyerDeadlinesViewState, BUYER_TASK_ITEM_ACTIONS, buyerTaskItemActions, buyerDeadlineTaskRow, buyerTaskVersion, buyerClosingDayProgress } from './handlers/buyerPlan.handler';
export { capitalTimelineBlock, renovationReadinessProgress } from './handlers/capitalPlanning.handler';
export { claimConflictDescription, CLAIM_TYPE_PATTERNS, ClaimFileWorkflowInputSchema, claimFileResult, incidentContinuationFromRecords, CLAIM_TRANSITION_ACTIONS, claimItemActions } from './handlers/claims.handler';
export { coverageComparisonStrip } from './handlers/coverage.handler';
export { DIY_ACTIVE_STATUSES, diyProjectsFromView } from './handlers/diyProjectCenter.handler';
export { doNothingSimulationFromView } from './handlers/doNothingSimulator.handler';
export { guidanceJourneysFromView } from './handlers/guidanceOverview.handler';
export { hoaComplianceFromView } from './handlers/hoaCompliance.handler';
export { isAllPropertyAttentionRequest, buildAllPropertyHomeActionSection, formatUnavailableHomeActionProducers, homeActionShelfFacts } from './handlers/homeActions.handler';
export { digitalWillHandoffProgress, digitalWillFromView } from './handlers/homeDigitalWill.handler';
export { parseRadarFeedFilters, radarFeedFilterMessage, RADAR_STATE_MESSAGES, RADAR_MARK_DONE_MESSAGE, RADAR_FEEDBACK_MESSAGE, RADAR_TASK_MESSAGE, RADAR_PREFERENCES_MESSAGE, RADAR_USER_STATE_LABEL, RADAR_FEEDBACK_OPTIONS, radarEventHref, radarEventItemActions, radarStateTransition, radarStateContextVersion, homeEventRadarStateResult, radarFeedbackConfirmation, RADAR_FEEDBACK_REVIEW_BODY, radarConfirmError, radarWriteReceipt, RADAR_TASK_CAPTURE_KEY, RADAR_PREFERENCES_CAPTURE_KEY, radarZonedWallClockToUtc, radarDateTimeLabel, radarTaskContextVersion, radarCaptureError, radarTaskFormResult, RADAR_TASK_CONFIRM_ERRORS, radarPreferencesContextVersion, radarPreferencesBodyFromAnswer, radarPreferenceLabels, radarPreferencesFormResult, RadarFeedLifecycleFilter, RadarFeedFamilyFilter, RadarFeedFilterState, RadarStateRequest } from './handlers/homeEventRadar.handler';
export { HOME_HABITS_ASK_LIMIT, homeHabitsFromView } from './handlers/homeHabitCoach.handler';
export { householdService, householdWorkflowVersion, householdInvitationResult, homeEventCorrectionValueError, homeEventFieldCurrent, homeEventFieldPatch, homeEventLinkOptions, homeEventCorrectionBlocker, homeEventContextVersion, homeEventCorrectionConfirmation, homeEventVisibilityBlocker, homeEventVisibilityConfirmation, WARRANTY_CORRECTION_FIELDS, warrantyCorrectionValueError, warrantyFieldCurrent, warrantyFieldPatch, warrantyContextVersion, warrantyCorrectionItemActions, warrantyCorrectionConfirmation, warrantyAddResult, eventAddResult, evidenceAttachResult, roomTypeLabel, ROOM_CORRECTION_FIELDS, roomFieldCurrent, roomFieldDisplay, roomContextVersion, roomCorrectionValueError, roomCorrectionNormalized, roomRenameItemActions, roomRenameConfirmation, EVENT_ADD_MESSAGE, WARRANTY_ADD_MESSAGE, ROOM_ADD_MESSAGE, ROOM_CREATE_CAPTURE_KEY, roomCreateContextVersion, roomCreateResult, homeEventsServiceForCapture } from './handlers/homeRecordWrites.handler';
export { pastHazardExposureFromView } from './handlers/homeRiskReplay.handler';
export { HOME_TIMELINE_ASK_LIMIT, roomMapFacts, homeTimelineCategory, homeTimelinePlacement, homeTimelineFromView } from './handlers/homeTimeline.handler';
export { homeUpgradeComparison, homeUpgradeScenariosFromView } from './handlers/homeUpgradePlanner.handler';
export { hvacDecisionStartContextVersion, hvacDecisionThreadVersionFingerprint, HVAC_VERDICT_RANK, hvacDecisionStartResult, hvacSpecialistEngageResult, HvacSpecialistEngageDependencies } from './handlers/hvacDecision.handler';
export { INSPECTION_FINDING_ACTIONS, inspectionFindingItemActions, inspectionFindingActionAllowed, inspectionFindingItemActionsFor, INSPECTION_FINDING_BATCH_ACTIONS, INSPECTION_FINDING_DECK_PRESENTATION, inspectionFindingDeckFacts, inspectionHubHref, INSPECTION_RESOLUTION_DEFAULT, inspectionResolutionEditableFields, inspectionFindingVersion } from './handlers/inspection.handler';
export { inventoryService, inventoryCategoryLabel, INVENTORY_CORRECTION_NO_ROOM_VALUE, INVENTORY_CORRECTION_FIELDS, INVENTORY_ROOM_LINK_FIELD, inventoryFieldCurrent, inventoryFieldValueError, inventoryRoomLinkOptions, inventoryCorrectionCombinedBlocker, inventoryFieldNormalized, inventoryFieldPatch, inventoryFieldDisplay, inventoryItemContextVersion, inventoryCorrectionItemActions, inventoryCorrectionConfirmation, INVENTORY_ADD_MESSAGE, INVENTORY_CREATE_CAPTURE_KEY, INVENTORY_NO_ROOM_VALUE, inventoryAddItemAction, inventoryCreateRooms, inventoryCreateContextVersion, inventoryCreateBlocker, inventoryItemCreateResult } from './handlers/inventory.handler';
export { maintenanceMoney, maintenanceWorkflowVersion, extractMaintenanceDueDate, maintenanceTaskCreateResult, maintenanceTaskVersion, maintenanceConflictDescription, maintenanceCompletionMatch, extractMaintenanceCompletionInput, maintenanceTaskCompleteResult, maintenanceUpdateAction, maintenanceUpdateSubject, maintenanceTaskUpdateResult, maintenanceMonitorSubject, loadAskViewState, mergeMaintenanceViewContinuation, maintenanceOpenTimingGroups, maintenanceShelfFacts, resolveMaintenanceCollectionOffset, maintenanceResult } from './handlers/maintenance.handler';
export { materialSpecsFromView } from './handlers/materialSpecs.handler';
export { NEGOTIATION_SHIELD_ASK_LIMIT, negotiationShieldCasesFromView } from './handlers/negotiationShield.handler';
export { plantCareOutlookFromView } from './handlers/plantAdvisor.handler';
export { PRICE_FINALIZATION_ASK_LIMIT, priceFinalizationsFromView } from './handlers/priceFinalization.handler';
export { trackedProjectsFromView } from './handlers/projectTracker.handler';
export { propertyBriefsFromView } from './handlers/propertyBrief.handler';
export { propertyCompletenessProgress, areaCaptureRowActions, areaCaptureStateFrom, AreaCaptureAnswerSchema, areaCaptureError, areaCapturePrompt, areaCaptureSubmitResult } from './handlers/propertySummary.handler';
export { areaCaptureFallbackHref } from './askHandlerSupport';
export { quoteWorkspaceContextVersion, quoteComparisonWorkspaceHref, QUOTE_LOWEST_PRICE_BADGE, quoteReviewComparison } from './handlers/quotes.handler';
export { refinanceMonitorContextVersion, parseRefinanceScenarioEdit, refinanceMonitorBlock, breakEvenHorizonYears, breakEvenAnalysisFromDto, refinanceScenarioComparison } from './handlers/refinance.handler';
export { SALE_READINESS_ITEM_STATUS_LABELS, sellHoldRentComparison, sellerPrepShelfFacts, SELLER_PREP_ITEM_ACTIONS, sellerPrepItemActions, saleCaseHref, sellerPrepItemContextVersion } from './handlers/sellHoldRent.handler';
export { SERVICE_PRICE_RADAR_ASK_LIMIT, servicePriceChecksFromView } from './handlers/servicePriceRadar.handler';
export { STATUS_BOARD_ASK_LIMIT, statusBoardShelfFacts, statusBoardMeta, statusBoardFromView } from './handlers/statusBoard.handler';

