import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  KNOWLEDGE_CATEGORY_SEEDS,
  KNOWLEDGE_TAG_SEEDS,
  PRODUCT_TOOL_SEEDS,
} from './knowledgeHub.seed';

export const KNOWLEDGE_HUB_PGADMIN_SEED_PATH =
  resolve(__dirname, 'knowledgeHub.pgadmin.seed.sql');

function literal(value: string | number | boolean | null): string {
  if (value === null) return 'NULL';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
  return `'${value.replace(/'/g, "''")}'`;
}

function jsonLiteral(value: unknown): string {
  return `${literal(JSON.stringify(value))}::jsonb`;
}

function values(rows: string[][]): string {
  return rows.map((row) => `  (${row.join(', ')})`).join(',\n');
}

const categories = values(KNOWLEDGE_CATEGORY_SEEDS.map((item) => [
  literal(item.slug),
  literal(item.name),
  literal(item.description),
  literal(item.sortOrder),
  literal(item.isActive),
]));

const tags = values(KNOWLEDGE_TAG_SEEDS.map((item) => [
  literal(item.slug),
  literal(item.name),
  literal(item.tagGroup),
  literal(item.isActive),
]));

const productTools = values(PRODUCT_TOOL_SEEDS.map((item) => [
  literal(item.key),
  literal(item.slug),
  literal(item.name),
  literal(item.shortDescription),
  `${literal(item.toolType)}::"ProductToolType"`,
  `${literal(item.status)}::"ProductToolStatus"`,
  literal(item.routePath),
  literal(item.iconName),
  literal(item.badgeLabel),
  literal(item.sortOrder),
  literal(item.category),
  jsonLiteral(item.metadata),
]));

export function renderKnowledgeHubPgAdminSeedSql(): string {
  return `-- Generated by prisma/generateKnowledgeHubPgAdminSeed.ts.
-- Source of truth: the canonical capability registry plus Knowledge Hub reference seeds.
-- Run this entire file in pgAdmin Query Tool against the target ContractToCozy database.
-- It is idempotent and non-destructive: existing article, CTA, event, and relation rows are untouched.

BEGIN;

INSERT INTO "knowledge_categories"
  ("slug", "name", "description", "sortOrder", "isActive")
VALUES
${categories}
ON CONFLICT ("slug") DO UPDATE SET
  "name" = EXCLUDED."name",
  "description" = EXCLUDED."description",
  "sortOrder" = EXCLUDED."sortOrder",
  "isActive" = EXCLUDED."isActive",
  "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "knowledge_tags"
  ("slug", "name", "tagGroup", "isActive")
VALUES
${tags}
ON CONFLICT ("slug") DO UPDATE SET
  "name" = EXCLUDED."name",
  "tagGroup" = EXCLUDED."tagGroup",
  "isActive" = EXCLUDED."isActive",
  "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "product_tools"
  ("key", "slug", "name", "shortDescription", "toolType", "status",
   "routePath", "iconName", "badgeLabel", "sortOrder", "category", "metadata")
VALUES
${productTools}
ON CONFLICT ("key") DO UPDATE SET
  "slug" = EXCLUDED."slug",
  "name" = EXCLUDED."name",
  "shortDescription" = EXCLUDED."shortDescription",
  "toolType" = EXCLUDED."toolType",
  "status" = EXCLUDED."status",
  "routePath" = EXCLUDED."routePath",
  "iconName" = EXCLUDED."iconName",
  "badgeLabel" = EXCLUDED."badgeLabel",
  "sortOrder" = EXCLUDED."sortOrder",
  "category" = EXCLUDED."category",
  "metadata" = EXCLUDED."metadata",
  "updatedAt" = CURRENT_TIMESTAMP;

COMMIT;

SELECT 'knowledge_categories' AS entity, COUNT(*) AS seeded_rows
FROM "knowledge_categories"
WHERE "slug" IN (${KNOWLEDGE_CATEGORY_SEEDS.map((item) => literal(item.slug)).join(', ')})
UNION ALL
SELECT 'knowledge_tags', COUNT(*)
FROM "knowledge_tags"
WHERE "slug" IN (${KNOWLEDGE_TAG_SEEDS.map((item) => literal(item.slug)).join(', ')})
UNION ALL
SELECT 'product_tools', COUNT(*)
FROM "product_tools"
WHERE "key" IN (${PRODUCT_TOOL_SEEDS.map((item) => literal(item.key)).join(', ')});
`;
}

if (require.main === module) {
  writeFileSync(
    KNOWLEDGE_HUB_PGADMIN_SEED_PATH,
    renderKnowledgeHubPgAdminSeedSql(),
  );
  console.log(`Generated ${KNOWLEDGE_HUB_PGADMIN_SEED_PATH}`);
  console.log(
    `${KNOWLEDGE_CATEGORY_SEEDS.length} categories, `
    + `${KNOWLEDGE_TAG_SEEDS.length} tags, `
    + `${PRODUCT_TOOL_SEEDS.length} product tools`,
  );
}
