-- Contract-to-Cozy seasonal task template seed for pgAdmin
--
-- DATA SEED ONLY. This is not a schema migration. Generated from apps/backend/src/data/seasonalTaskTemplates.json (44 templates,
-- including the three TROPICAL fall templates added October 5, 2026). Run it after `prisma db push` has created the tables and enum types.
-- It never deletes anything and never touches user data. It is idempotent: it upserts each template by task_key and may be run again.
--
-- NOTE: unlike prisma/seasonalTasks.seed.ts, this also writes required_asset_type, required_asset_check and timing_offset_days, which that
-- script ignores. For templates that already exist, running this sets those three columns from the JSON (asset-gated templates such as
-- SPRING_HVAC_AC_INSPECTION will start to require their asset). If you do not want that, delete the three columns from the INSERT list, the
-- VALUES rows and the DO UPDATE SET list.

BEGIN;

INSERT INTO "seasonal_task_templates"
  ("id", "task_key", "season", "title", "description", "why_it_matters",
   "typical_cost_min", "typical_cost_max", "is_diy_possible", "estimated_hours",
   "priority", "service_category", "climate_regions", "required_asset_type",
   "required_asset_check", "timing_offset_days", "recurrence_pattern",
   "is_active", "created_at", "updated_at")
VALUES
  (gen_random_uuid()::text, 'SPRING_HVAC_AC_INSPECTION', 'SPRING', 'AC system inspection and tune-up', 'Professional inspection and maintenance of air conditioning system before summer heat', 'Prevents breakdowns during peak summer when repairs are most expensive and wait times are longest. Improves efficiency by up to 15%.', 100, 200, false, 1.5, 'CRITICAL', 'HVAC', ARRAY['VERY_COLD','COLD','MODERATE','WARM','TROPICAL']::"ClimateRegion"[], NULL, 'has_ac', -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'SPRING_GUTTER_CLEANING', 'SPRING', 'Gutter cleaning and inspection', 'Remove debris from gutters and downspouts, inspect for damage', 'Prevents water damage to foundation, basement flooding, and ice dams. Clogged gutters can cause $1000+ in water damage.', 150, 300, true, 2.0, 'CRITICAL', 'EXTERIOR', ARRAY['VERY_COLD','COLD','MODERATE','WARM','TROPICAL']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'SPRING_WINDOW_SCREEN_REPAIR', 'SPRING', 'Window and door screen repair', 'Inspect and repair or replace damaged window and door screens', 'Keeps insects out during warmer months and improves ventilation without pests.', 50, 150, true, 2.0, 'RECOMMENDED', 'WINDOWS', ARRAY['VERY_COLD','COLD','MODERATE','WARM','TROPICAL']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'SPRING_EXTERIOR_PAINT_INSPECTION', 'SPRING', 'Exterior paint inspection and touch-ups', 'Check exterior paint for peeling, cracking, or fading. Touch up problem areas.', 'Prevents wood rot and extends the life of your siding. Early touch-ups prevent costly full repaints.', 100, 500, true, 4.0, 'RECOMMENDED', 'EXTERIOR', ARRAY['VERY_COLD','COLD','MODERATE','WARM','TROPICAL']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'SPRING_WATER_HEATER_FLUSH', 'SPRING', 'Water heater drain and flush', 'Drain sediment from water heater tank to improve efficiency', 'Sediment buildup reduces efficiency and can shorten tank life by 50%. Flushing extends lifespan and lowers energy costs.', 75, 150, true, 1.0, 'RECOMMENDED', 'PLUMBING', ARRAY['VERY_COLD','COLD','MODERATE','WARM','TROPICAL']::"ClimateRegion"[], 'WATER_HEATER', NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'SPRING_LAWN_CARE_STARTUP', 'SPRING', 'Lawn care startup (fertilizer, aeration)', 'Apply spring fertilizer, perform aeration if needed, overseed bare spots', 'Spring is critical for establishing healthy grass that crowds out weeds all summer.', 100, 300, true, 3.0, 'OPTIONAL', 'LANDSCAPING', ARRAY['VERY_COLD','COLD','MODERATE','WARM']::"ClimateRegion"[], NULL, 'has_lawn', -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'SPRING_DECK_CLEANING_SEALING', 'SPRING', 'Deck/patio cleaning and sealing', 'Power wash deck, inspect for damage, apply sealant if needed', 'Protects wood from moisture and UV damage. Prevents expensive deck replacement.', 200, 600, true, 6.0, 'RECOMMENDED', 'EXTERIOR', ARRAY['VERY_COLD','COLD','MODERATE','WARM','TROPICAL']::"ClimateRegion"[], 'DECK', 'has_deck', -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'SPRING_ROOF_INSPECTION', 'SPRING', 'Roof inspection for winter damage', 'Professional or DIY inspection for missing shingles, leaks, or damage', 'Winter weather can damage roofs. Early detection prevents interior water damage.', 150, 300, true, 2.0, 'CRITICAL', 'ROOFING', ARRAY['VERY_COLD','COLD','MODERATE','WARM']::"ClimateRegion"[], 'ROOF', NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'SPRING_SMOKE_CO_DETECTOR_TEST', 'SPRING', 'Test smoke/CO detectors, replace batteries', 'Test all smoke and carbon monoxide detectors, replace batteries', 'Critical safety measure. Detectors save lives but only if they''re working.', 20, 50, true, 0.5, 'CRITICAL', 'SAFETY', ARRAY['VERY_COLD','COLD','MODERATE','WARM','TROPICAL']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'SPRING_IRRIGATION_STARTUP', 'SPRING', 'Irrigation system startup and leak check', 'Turn on irrigation system, check for leaks, adjust sprinkler heads', 'Catches winter damage before it wastes hundreds of dollars in water.', 75, 150, true, 1.5, 'RECOMMENDED', 'LANDSCAPING', ARRAY['WARM','MODERATE']::"ClimateRegion"[], 'IRRIGATION', 'has_sprinkler_system', -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'SUMMER_AC_FILTER_CHANGE', 'SUMMER', 'Replace AC filters monthly', 'Check and replace HVAC filters every month during peak cooling season', 'Dirty filters reduce efficiency by 15% and strain your AC system, leading to early failure.', 15, 40, true, 0.25, 'CRITICAL', 'HVAC', ARRAY['COLD','MODERATE','WARM','TROPICAL']::"ClimateRegion"[], NULL, 'has_ac', -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'SUMMER_POWER_WASH_SIDING', 'SUMMER', 'Power wash siding and walkways', 'Clean exterior siding, walkways, and driveways to remove dirt and mildew', 'Prevents mold growth and maintains curb appeal. Extends life of siding.', 200, 500, true, 4.0, 'RECOMMENDED', 'EXTERIOR', ARRAY['VERY_COLD','COLD','MODERATE','WARM','TROPICAL']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'SUMMER_OUTDOOR_FAUCET_CHECK', 'SUMMER', 'Inspect outdoor faucets and hoses', 'Check outdoor faucets for leaks, replace worn hoses', 'Small leaks can waste thousands of gallons and damage foundations.', 50, 150, true, 1.0, 'RECOMMENDED', 'PLUMBING', ARRAY['VERY_COLD','COLD','MODERATE','WARM','TROPICAL']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'SUMMER_TREE_TRIMMING', 'SUMMER', 'Trim trees and shrubs away from house', 'Cut back branches touching roof or siding, trim overgrown shrubs', 'Prevents roof damage, reduces pest entry points, and improves air circulation.', 200, 600, true, 4.0, 'RECOMMENDED', 'LANDSCAPING', ARRAY['VERY_COLD','COLD','MODERATE','WARM','TROPICAL']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'SUMMER_DRYER_VENT_CLEANING', 'SUMMER', 'Inspect and clean dryer vent', 'Clean dryer vent from inside and outside to remove lint buildup', 'Prevents dryer fires (15,000/year in US) and improves efficiency.', 100, 200, true, 1.5, 'CRITICAL', 'APPLIANCES', ARRAY['VERY_COLD','COLD','MODERATE','WARM','TROPICAL']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'SUMMER_PEST_TREATMENT', 'SUMMER', 'Ant and termite prevention treatment', 'Apply preventative pest treatment around foundation and entry points', 'Summer is peak pest season. Prevention is 10x cheaper than treatment.', 100, 300, true, 2.0, 'RECOMMENDED', 'PEST', ARRAY['COLD','MODERATE','WARM','TROPICAL']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'SUMMER_OUTDOOR_ELECTRICAL_CHECK', 'SUMMER', 'Check grounding of outdoor electrical outlets', 'Test GFCI outlets, inspect outdoor electrical for safety', 'Prevents electrical shock and fires from weather exposure.', 75, 150, false, 1.0, 'RECOMMENDED', 'ELECTRICAL', ARRAY['VERY_COLD','COLD','MODERATE','WARM','TROPICAL']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'SUMMER_POOL_INSPECTION', 'SUMMER', 'Inspect and clean pool/spa', 'Full pool inspection, chemical balance check, filter cleaning', 'Prevents algae growth and equipment damage. Ensures safe swimming conditions.', 150, 350, true, 3.0, 'CRITICAL', 'POOL', ARRAY['WARM','TROPICAL']::"ClimateRegion"[], 'POOL', 'has_pool', -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'SUMMER_HURRICANE_PREP', 'SUMMER', 'Hurricane preparedness checklist', 'Check storm shutters, generator, emergency supplies, create evacuation plan', 'Hurricane season runs June-November. Preparation can save lives and property.', 200, 1000, true, 6.0, 'CRITICAL', 'SAFETY', ARRAY['WARM','TROPICAL']::"ClimateRegion"[], NULL, 'is_coastal', -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'FALL_FURNACE_INSPECTION', 'FALL', 'Furnace inspection and tune-up', 'Professional inspection and maintenance of heating system before winter', 'Prevents mid-winter breakdowns when repairs are most expensive. Improves efficiency and safety.', 100, 200, false, 1.5, 'CRITICAL', 'HVAC', ARRAY['VERY_COLD','COLD','MODERATE','WARM']::"ClimateRegion"[], 'FURNACE', NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'FALL_GUTTER_CLEANING_LEAVES', 'FALL', 'Gutter cleaning (leaves)', 'Remove fallen leaves from gutters and downspouts', 'Critical before winter. Prevents ice dams that can cause thousands in damage.', 150, 300, true, 2.0, 'CRITICAL', 'EXTERIOR', ARRAY['VERY_COLD','COLD','MODERATE','WARM']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'FALL_CHIMNEY_CLEANING', 'FALL', 'Chimney cleaning and inspection', 'Professional chimney sweep and safety inspection', 'Prevents chimney fires and carbon monoxide poisoning. Required for insurance.', 150, 250, false, 2.0, 'CRITICAL', 'CHIMNEY', ARRAY['VERY_COLD','COLD','MODERATE']::"ClimateRegion"[], 'CHIMNEY', 'has_fireplace', -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'FALL_DRAIN_OUTDOOR_FAUCETS', 'FALL', 'Drain outdoor faucets and sprinkler system', 'Disconnect hoses, drain outdoor faucets, winterize irrigation', 'Frozen pipes can burst and cause $5,000+ in damage. Simple prevention saves thousands.', 50, 100, true, 1.0, 'CRITICAL', 'PLUMBING', ARRAY['VERY_COLD','COLD','MODERATE']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'FALL_STORM_WINDOWS', 'FALL', 'Install storm windows or check weatherstripping', 'Install storm windows if applicable, check and replace weatherstripping', 'Reduces heating costs by 10-25% and improves comfort.', 100, 500, true, 4.0, 'RECOMMENDED', 'WINDOWS', ARRAY['VERY_COLD','COLD','MODERATE']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'FALL_LAWN_FERTILIZE', 'FALL', 'Fertilize lawn for winter', 'Apply fall fertilizer to strengthen grass roots for winter', 'Fall feeding helps grass survive winter and green up faster in spring.', 50, 150, true, 2.0, 'OPTIONAL', 'LANDSCAPING', ARRAY['VERY_COLD','COLD','MODERATE']::"ClimateRegion"[], NULL, 'has_lawn', -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'FALL_SEAL_DRIVEWAY', 'FALL', 'Seal driveway cracks before freezing', 'Fill cracks in driveway and apply sealant if needed', 'Water in cracks freezes and expands, causing major damage. Prevention is 10x cheaper than repair.', 200, 500, true, 4.0, 'RECOMMENDED', 'EXTERIOR', ARRAY['VERY_COLD','COLD','MODERATE']::"ClimateRegion"[], 'DRIVEWAY', 'has_driveway', -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'FALL_CO_DETECTOR_CHECK', 'FALL', 'Check carbon monoxide detectors', 'Test CO detectors and replace batteries before heating season', 'CO poisoning peaks in winter. Detectors save lives but only if working properly.', 15, 50, true, 0.5, 'CRITICAL', 'SAFETY', ARRAY['VERY_COLD','COLD','MODERATE','WARM']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'FALL_CEILING_FAN_REVERSE', 'FALL', 'Reverse ceiling fan direction', 'Switch ceiling fans to clockwise rotation for winter', 'Pushes warm air down, can reduce heating costs by 10%.', 0, 0, true, 0.5, 'OPTIONAL', 'HVAC', ARRAY['VERY_COLD','COLD','MODERATE']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'FALL_WINTERIZE_SPRINKLERS', 'FALL', 'Winterize sprinkler system (blow out lines)', 'Professional blow-out of sprinkler system to prevent freeze damage', 'Prevents $500+ in pipe replacement costs from freeze damage.', 75, 150, false, 1.0, 'CRITICAL', 'LANDSCAPING', ARRAY['VERY_COLD','COLD']::"ClimateRegion"[], 'IRRIGATION', 'has_sprinkler_system', -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'FALL_ATTIC_INSULATION_CHECK', 'FALL', 'Inspect insulation in attic and basement', 'Check for adequate insulation levels and air leaks', 'Poor insulation can waste 25% of heating costs. ROI is typically under 2 years.', 100, 300, true, 2.0, 'RECOMMENDED', 'INSULATION', ARRAY['VERY_COLD','COLD']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'WINTER_FURNACE_FILTER_CHANGE', 'WINTER', 'Replace furnace filters monthly', 'Check and replace HVAC filters every month during peak heating season', 'Dirty filters reduce efficiency and can cause furnace failure in extreme cold.', 15, 40, true, 0.25, 'CRITICAL', 'HVAC', ARRAY['VERY_COLD','COLD','MODERATE']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'WINTER_GFCI_OUTLET_TEST', 'WINTER', 'Test GFCI outlets', 'Test all GFCI outlets in bathrooms, kitchen, garage, and outdoors', 'Prevents electrical shock. Critical safety measure that takes 5 minutes.', 0, 0, true, 0.5, 'CRITICAL', 'ELECTRICAL', ARRAY['VERY_COLD','COLD','MODERATE','WARM','TROPICAL']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'WINTER_SINK_LEAK_CHECK', 'WINTER', 'Check for leaks under sinks', 'Inspect under-sink plumbing for leaks and corrosion', 'Small leaks can cause major water damage and mold. Easy to catch early.', 0, 0, true, 0.5, 'RECOMMENDED', 'PLUMBING', ARRAY['VERY_COLD','COLD','MODERATE','WARM','TROPICAL']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'WINTER_HUMIDITY_CHECK', 'WINTER', 'Check and adjust humidity levels (30-50%)', 'Monitor indoor humidity and adjust humidifier/dehumidifier as needed', 'Low humidity damages wood floors and furniture. High humidity causes mold.', 50, 200, true, 1.0, 'RECOMMENDED', 'HVAC', ARRAY['VERY_COLD','COLD','MODERATE']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'WINTER_PIPE_INSULATION_CHECK', 'WINTER', 'Inspect insulation around pipes in unheated areas', 'Check pipe insulation in attic, basement, garage, and crawl spaces', 'Frozen pipes are the #1 winter home disaster, averaging $5,000+ in damage.', 50, 200, true, 2.0, 'CRITICAL', 'PLUMBING', ARRAY['VERY_COLD','COLD']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'WINTER_ICE_DAM_REMOVAL', 'WINTER', 'Remove ice dams from roof', 'Safely remove ice dams when they form, or install prevention systems', 'Ice dams can cause catastrophic roof and interior damage.', 200, 800, false, 3.0, 'CRITICAL', 'ROOFING', ARRAY['VERY_COLD','COLD']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'WINTER_FROZEN_PIPE_MONITOR', 'WINTER', 'Monitor for frozen pipes', 'Regular checks of vulnerable pipes, keep heat on, let faucets drip in extreme cold', 'Vigilance prevents burst pipes. Insurance claims average $10,000.', 0, 0, true, 1.0, 'CRITICAL', 'PLUMBING', ARRAY['VERY_COLD','COLD']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'WINTER_SNOW_CLEAR_VENTS', 'WINTER', 'Clear snow from vents', 'Keep furnace, dryer, and other vents clear of snow buildup', 'Blocked vents can cause carbon monoxide poisoning or equipment damage.', 0, 0, true, 0.5, 'CRITICAL', 'SAFETY', ARRAY['VERY_COLD','COLD']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'WINTER_TREE_PRUNING', 'WINTER', 'Prune dormant trees and shrubs', 'Trim dead branches and shape trees while dormant', 'Winter is ideal for pruning. Prevents storm damage to trees and property.', 150, 500, true, 4.0, 'OPTIONAL', 'LANDSCAPING', ARRAY['WARM','TROPICAL']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'WINTER_ROOF_SNOW_LOAD', 'WINTER', 'Check roof for snow load', 'Monitor snow accumulation on roof, remove if excessive', 'Excessive snow can cause roof collapse. Warning signs: sagging ceilings, cracking noises.', 200, 600, false, 3.0, 'CRITICAL', 'ROOFING', ARRAY['VERY_COLD']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'WINTER_FOUNDATION_SNOW_CLEAR', 'WINTER', 'Keep snow away from foundation', 'Clear snow from around foundation to prevent water infiltration during thaw', 'Snow melt can flood basements and damage foundations.', 0, 0, true, 1.0, 'RECOMMENDED', 'EXTERIOR', ARRAY['VERY_COLD','COLD']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'FALL_TROPICAL_STORM_READINESS', 'FALL', 'Review storm readiness for the rest of hurricane season', 'Check storm supplies, an evacuation plan and a way to protect windows and doors, and know where your shutoffs are', 'Tropical storm season runs into late fall. Being ready before a storm warning avoids rushed, costly decisions.', 25, 150, true, 1.0, 'CRITICAL', 'SAFETY', ARRAY['TROPICAL']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'FALL_TROPICAL_DRAINAGE_CHECK', 'FALL', 'Clear gutters, downspouts and yard drains of debris', 'Remove leaves and debris so heavy tropical rain drains away from the house', 'Fall storms can drop a lot of rain quickly. Blocked drainage sends water toward the foundation and under roofing.', 0, 200, true, 1.5, 'RECOMMENDED', 'EXTERIOR', ARRAY['TROPICAL']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now()),
  (gen_random_uuid()::text, 'FALL_TROPICAL_MOISTURE_CHECK', 'FALL', 'Check for moisture and mold after the wet season', 'Look in bathrooms, closets, the attic and under sinks for damp spots, musty smells or mold, and run exhaust fans', 'Humid, wet weather lets mold start quietly. Catching damp spots early keeps repairs small.', 0, 100, true, 1.0, 'RECOMMENDED', 'SAFETY', ARRAY['TROPICAL']::"ClimateRegion"[], NULL, NULL, -14, 'ANNUAL', true, now(), now())
ON CONFLICT ("task_key") DO UPDATE SET
  "season" = EXCLUDED."season",
  "title" = EXCLUDED."title",
  "description" = EXCLUDED."description",
  "why_it_matters" = EXCLUDED."why_it_matters",
  "typical_cost_min" = EXCLUDED."typical_cost_min",
  "typical_cost_max" = EXCLUDED."typical_cost_max",
  "is_diy_possible" = EXCLUDED."is_diy_possible",
  "estimated_hours" = EXCLUDED."estimated_hours",
  "priority" = EXCLUDED."priority",
  "service_category" = EXCLUDED."service_category",
  "climate_regions" = EXCLUDED."climate_regions",
  "required_asset_type" = EXCLUDED."required_asset_type",
  "required_asset_check" = EXCLUDED."required_asset_check",
  "timing_offset_days" = EXCLUDED."timing_offset_days",
  "recurrence_pattern" = EXCLUDED."recurrence_pattern",
  "is_active" = EXCLUDED."is_active",
  "updated_at" = now();

COMMIT;

-- Verification: expect 44 rows from this seed (more if other templates exist), and the three new tropical fall rows below.
SELECT count(*) AS seasonal_task_templates FROM "seasonal_task_templates";
SELECT "task_key", "season", "priority", "climate_regions"
FROM "seasonal_task_templates"
WHERE "task_key" LIKE 'FALL_TROPICAL_%'
ORDER BY "task_key";
