// apps/backend/src/config/workerJobRegistry.ts
//
// Single source of truth for all background worker jobs.
//
// IMPORTANT — when adding a new job to apps/workers/src/worker.ts:
//   1. Add an entry to JOB_REGISTRY below (this file)
//   2. Add the handler to CRON_HANDLERS in apps/workers/src/worker.ts
//   3. If it's a new category, add it to the JobCategory union type here
//      AND to CATEGORY_ORDER in apps/frontend/.../worker-jobs/page.tsx
//   4. Add a WorkerExecutionPolicy block (impact/customerJob/etc) — see
//      apps/backend/src/config/workerExecutionPolicy.ts. The scheduler,
//      manual cron-trigger queue, and runners all gate on this via
//      evaluateWorkerExecution(), so a job with no policy metadata will not
//      run in beta.
//
// The worker reads cron expressions from this registry at startup.
// A handler with no registry entry will log a warning at startup.
// A registry entry with no handler will also log a warning and not run.

import type { WorkerExecutionPolicy } from './workerExecutionPolicy';

export type JobCategory =
  | 'PROPERTY_INTELLIGENCE'
  | 'RECALLS'
  | 'NOTIFICATIONS'
  | 'MAINTENANCE'
  | 'RISK_SAFETY'
  | 'NEIGHBORHOOD'
  | 'HOME_CARE'
  | 'FINANCIAL_MARKET'
  | 'HOME_INTELLIGENCE'
  | 'DIY_TEMPLATES';

export interface JobRegistryEntry extends WorkerExecutionPolicy {
  key: string;
  name: string;
  description: string;
  category: JobCategory;
  schedule: string;
  cronExpression: string;
  /** bullmq = has a BullMQ queue; cron = node-cron only */
  type: 'bullmq' | 'cron';
  queueName?: string;
  jobName?: string;
  triggerSupported: boolean;
}

export const LEGACY_WORKER_JOB_KEY_ALIASES: Readonly<Record<string, string>> = {
  'home-gazette-generation': 'home-briefing-delivery',
};

export function canonicalWorkerJobKey(jobKey: string): string {
  return LEGACY_WORKER_JOB_KEY_ALIASES[jobKey] ?? jobKey;
}

export const JOB_REGISTRY: JobRegistryEntry[] = [
  // ── Property Intelligence (BullMQ, event-driven) ──────────────────────────
  {
    key: 'property-intelligence',
    name: 'Property Intelligence',
    description:
      'Calculates risk report and hidden asset matches per property. Enqueued automatically when a property is updated.',
    category: 'PROPERTY_INTELLIGENCE',
    schedule: 'On-demand (event-driven)',
    cronExpression: '',
    type: 'bullmq',
    queueName: 'property-intelligence-queue',
    triggerSupported: false,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: true,
    humanApprovalClass: 'NONE',
  },

  // ── Recalls (BullMQ repeatable) ───────────────────────────────────────────
  {
    key: 'recall-ingest',
    name: 'Recall Ingest',
    description:
      'Ingests the latest product safety recalls from the CPSC database and stores new recall records.',
    category: 'RECALLS',
    schedule: 'Daily at 3:00 AM EST',
    cronExpression: '0 3 * * *',
    type: 'bullmq',
    queueName: 'recall-jobs-queue',
    jobName: 'recall.ingest',
    triggerSupported: true,
    impact: 'INTERNAL_WRITE',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: false,
    externalProvider: 'CPSC',
    humanApprovalClass: 'NONE',
  },
  {
    key: 'recall-match',
    name: 'Recall Match',
    description:
      'Matches newly ingested recalls against homeowner inventory and sends notifications for affected items.',
    category: 'RECALLS',
    schedule: 'Daily at 3:10 AM EST',
    cronExpression: '10 3 * * *',
    type: 'bullmq',
    queueName: 'recall-jobs-queue',
    jobName: 'recall.match',
    triggerSupported: true,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: false,
    humanApprovalClass: 'NONE',
  },

  // ── Notifications (BullMQ, event-driven) ──────────────────────────────────
  {
    key: 'email-notification',
    name: 'Email Notification',
    description: 'Sends queued email notifications (maintenance reminders, report alerts, etc.).',
    category: 'NOTIFICATIONS',
    schedule: 'On-demand (event-driven)',
    cronExpression: '',
    type: 'bullmq',
    queueName: 'email-notification-queue',
    triggerSupported: false,
    impact: 'OUTBOUND',
    customerJob: 'PLATFORM_OPERATIONS',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: false,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'push-notification',
    name: 'Push Notification',
    description: 'Sends queued push notifications to mobile devices. No push provider is implemented yet — inactive until WORKER_JOB_PUSH_NOTIFICATION_ENABLED=true and a provider is configured.',
    category: 'NOTIFICATIONS',
    schedule: 'On-demand (event-driven)',
    cronExpression: '',
    type: 'bullmq',
    queueName: 'push-notification-queue',
    triggerSupported: false,
    impact: 'OUTBOUND',
    customerJob: 'PLATFORM_OPERATIONS',
    defaultEnabledInBeta: false,
    supportsDryRun: false,
    supportsPropertyScope: false,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'sms-notification',
    name: 'SMS Notification',
    description: 'Sends queued SMS messages for high-priority alerts. No SMS provider is implemented yet — inactive until WORKER_JOB_SMS_NOTIFICATION_ENABLED=true and a provider is configured.',
    category: 'NOTIFICATIONS',
    schedule: 'On-demand (event-driven)',
    cronExpression: '',
    type: 'bullmq',
    queueName: 'sms-notification-queue',
    triggerSupported: false,
    impact: 'OUTBOUND',
    customerJob: 'PLATFORM_OPERATIONS',
    defaultEnabledInBeta: false,
    supportsDryRun: false,
    supportsPropertyScope: false,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'renovation-advisor-evaluation',
    name: 'Renovation Advisor Evaluation',
    description: 'Runs queued permit, tax, licensing, and zoning evaluations with bounded concurrency and retries.',
    category: 'HOME_INTELLIGENCE',
    schedule: 'On-demand (event-driven)',
    cronExpression: '',
    type: 'bullmq',
    queueName: 'renovation-evaluation-queue',
    jobName: 'evaluate-renovation-advisor-session',
    triggerSupported: false,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'MAJOR_MOMENT',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: true,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'daily-email-digest',
    name: 'Daily Email Digest',
    description: 'Sends a daily summary email to homeowners with pending maintenance and alerts.',
    category: 'NOTIFICATIONS',
    schedule: 'Daily at 8:00 AM EST',
    cronExpression: '0 8 * * *',
    type: 'cron',
    triggerSupported: false,
    impact: 'OUTBOUND',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: false,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'weekly-home-brief-digest',
    name: 'Weekly Home Brief Digest',
    description: 'Bundles routine notifications into the homeowner weekly Home Brief.',
    category: 'NOTIFICATIONS',
    schedule: 'Mondays at 8:00 AM EST',
    cronExpression: '0 8 * * 1',
    type: 'cron',
    triggerSupported: false,
    impact: 'OUTBOUND',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: false,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'home-operations-due-digest',
    name: 'Home Operations Due Digest',
    description:
      'Item #20 (Slice 8: "digest limited to changed or due work"). Emits a canonical PropertyChange for every ' +
      'OperationalWorkItem entering its reminder-policy due window, so it surfaces on the next hourly ' +
      'home-briefing-delivery run. Writes no user-facing state directly and is idempotent per (property, work ' +
      'item, dueAt) — safe to re-run.',
    category: 'NOTIFICATIONS',
    schedule: 'Daily at 7:00 AM EST',
    cronExpression: '0 7 * * *',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'home-operations-due-digest',
    triggerSupported: true,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: false,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'weekly-retention-report',
    name: 'Weekly Retention Report',
    description: 'Emails a weekly activation/retention/engagement summary (ProductAnalyticsEvent) to RETENTION_REPORT_EMAIL.',
    category: 'NOTIFICATIONS',
    schedule: 'Mondays at 8:00 AM EST',
    cronExpression: '0 8 * * 1',
    type: 'cron',
    triggerSupported: false,
    impact: 'OUTBOUND',
    customerJob: 'PLATFORM_OPERATIONS',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: false,
    humanApprovalClass: 'NONE',
  },

  // ── Maintenance (cron) ────────────────────────────────────────────────────
  {
    key: 'maintenance-reminders',
    name: 'Maintenance Reminders',
    description:
      'Sends maintenance reminder notifications to homeowners with upcoming or overdue canonical PropertyMaintenanceTask records via NotificationService (governed by preferences, cadence, and quiet hours).',
    category: 'MAINTENANCE',
    schedule: 'Daily at 9:00 AM EST',
    cronExpression: '0 9 * * *',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'maintenance-reminders',
    triggerSupported: true,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: true,
    humanApprovalClass: 'HIGH_IMPACT_MANUAL',
  },
  {
    key: 'new-home-warranty-deadlines',
    name: 'New-home Warranty Deadlines',
    description: 'Promotes verified builder and manufacturer warranty notice deadlines into canonical tasks and governed notifications.',
    category: 'MAINTENANCE',
    schedule: 'Daily at 8:30 AM EST',
    cronExpression: '30 8 * * *',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'new-home-warranty-deadlines',
    triggerSupported: true,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'MAJOR_MOMENT',
    defaultEnabledInBeta: true,
    supportsDryRun: true,
    supportsPropertyScope: true,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'seasonal-checklist-generation',
    name: 'Seasonal Checklist Generation',
    description:
      'Generates seasonal home maintenance checklists for all properties at the start of each season.',
    category: 'MAINTENANCE',
    schedule: 'Daily at 2:00 AM EST',
    cronExpression: '0 2 * * *',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'seasonal-checklist-generation',
    triggerSupported: true,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: true,
    broadSweep: true,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'seasonal-checklist-expiration',
    name: 'Seasonal Checklist Expiration',
    description: 'Marks expired seasonal checklists as closed at the end of each season.',
    category: 'MAINTENANCE',
    schedule: 'Daily at 1:00 AM EST',
    cronExpression: '0 1 * * *',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'seasonal-checklist-expiration',
    triggerSupported: true,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: true,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'seasonal-notifications',
    name: 'Seasonal Notifications',
    description:
      'Notifies homeowners of new seasonal checklists and upcoming seasonal tasks via NotificationService (governed by preferences, cadence, and quiet hours; outbound send gated by WORKER_OUTBOUND_NOTIFICATIONS_ENABLED).',
    category: 'MAINTENANCE',
    schedule: 'Daily at 9:00 AM EST',
    cronExpression: '0 9 * * *',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'seasonal-notifications',
    triggerSupported: true,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: true,
    humanApprovalClass: 'HIGH_IMPACT_MANUAL',
  },
  {
    key: 'inventory-draft-cleanup',
    name: 'Inventory Draft Cleanup',
    description:
      'Removes stale unfinished inventory drafts older than the configured retention window. Schedule overridable via INVENTORY_DRAFT_CLEANUP_CRON env var.',
    category: 'MAINTENANCE',
    schedule: 'Daily at 3:15 AM EST',
    cronExpression: '15 3 * * *',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'inventory-draft-cleanup',
    triggerSupported: true,
    impact: 'DESTRUCTIVE',
    customerJob: 'PLATFORM_OPERATIONS',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: false,
    broadSweep: true,
    humanApprovalClass: 'HIGH_IMPACT_MANUAL',
  },

  // ── Risk & Safety (cron) ──────────────────────────────────────────────────
  {
    key: 'coverage-lapse-incidents',
    name: 'Coverage Lapse Incidents',
    description:
      'Detects properties with coverage gaps and creates incident records for follow-up.',
    category: 'RISK_SAFETY',
    schedule: 'Daily at 8:00 AM EST',
    cronExpression: '0 8 * * *',
    type: 'cron',
    triggerSupported: false,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: true,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'freeze-risk-incidents',
    name: 'Freeze Risk Incidents',
    description:
      'Flags properties at elevated risk of pipe freeze based on temperature forecast and home profile.',
    category: 'RISK_SAFETY',
    schedule: 'Daily at 9:00 AM EST',
    cronExpression: '0 9 * * *',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'freeze-risk-incidents',
    triggerSupported: true,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: true,
    supportsDryRun: true,
    supportsPropertyScope: true,
    externalProvider: 'NOAA/NWS (forecast)',
    humanApprovalClass: 'NONE',
  },
  {
    key: 'severe-weather-alerts',
    name: 'Severe Weather Alerts',
    description:
      'Polls live NOAA/NWS alerts (flash flood, severe thunderstorm, tornado, high wind, excessive heat, winter storm) per property and creates incidents for active warnings.',
    category: 'RISK_SAFETY',
    schedule: 'Every 15 minutes',
    cronExpression: '*/15 * * * *',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'severe-weather-alerts',
    triggerSupported: true,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: true,
    supportsDryRun: true,
    supportsPropertyScope: true,
    externalProvider: 'NOAA/NWS',
    humanApprovalClass: 'NONE',
  },
  {
    key: 'airnow-air-quality',
    name: 'EPA AirNow Air Quality',
    description:
      'Polls current and forecast AirNow AQI by reporting area and emits canonical air-quality or smoke events at the EPA unhealthy threshold.',
    category: 'RISK_SAFETY',
    schedule: 'Every 30 minutes',
    cronExpression: '*/30 * * * *',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'airnow-air-quality',
    triggerSupported: true,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: false,
    supportsDryRun: true,
    supportsPropertyScope: true,
    externalProvider: 'EPA AirNow',
    humanApprovalClass: 'NONE',
  },
  {
    key: 'usgs-earthquakes',
    name: 'USGS Earthquakes',
    description:
      'Polls the USGS real-time GeoJSON feed and emits canonical earthquake events only when reviewed magnitude and property-distance thresholds are met.',
    category: 'RISK_SAFETY',
    schedule: 'Every 5 minutes',
    cronExpression: '*/5 * * * *',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'usgs-earthquakes',
    triggerSupported: true,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: false,
    supportsDryRun: true,
    supportsPropertyScope: true,
    externalProvider: 'U.S. Geological Survey',
    humanApprovalClass: 'NONE',
  },
  {
    key: 'openfema-declarations',
    name: 'OpenFEMA Disaster Declarations',
    description:
      'Polls OpenFEMA v2 disaster declarations by property state and emits county/state recovery-context events with exact FIPS matching.',
    category: 'RISK_SAFETY',
    schedule: 'Every 6 hours at minute 17',
    cronExpression: '17 */6 * * *',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'openfema-declarations',
    triggerSupported: true,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: false,
    supportsDryRun: true,
    supportsPropertyScope: true,
    externalProvider: 'FEMA OpenFEMA',
    humanApprovalClass: 'NONE',
  },
  {
    key: 'weekly-score-snapshots',
    name: 'Weekly Score Snapshots',
    description:
      'Captures a weekly snapshot of property health and risk scores for trend tracking.',
    category: 'RISK_SAFETY',
    schedule: 'Mondays at 4:00 AM EST',
    cronExpression: '0 4 * * 1',
    type: 'cron',
    triggerSupported: false,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: true,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'hidden-asset-refresh',
    name: 'Hidden Asset Batch Refresh',
    description:
      'Re-evaluates all properties for unrealized tax deductions, warranty coverage gaps, and untapped rebates.',
    category: 'RISK_SAFETY',
    schedule: 'Sundays at 3:00 AM EST',
    cronExpression: '0 3 * * 0',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'hidden-asset-refresh',
    triggerSupported: true,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'DECIDE',
    defaultEnabledInBeta: true,
    supportsDryRun: true,
    supportsPropertyScope: true,
    broadSweep: true,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'provider-credential-expire',
    name: 'Provider Credential Expire',
    description:
      'Transitions approved provider credentials past their expiry date to EXPIRED and recomputes affected providers\' category eligibility.',
    category: 'RISK_SAFETY',
    schedule: 'Daily at 6:00 AM EST',
    cronExpression: '0 6 * * *',
    type: 'cron',
    triggerSupported: false,
    impact: 'INTERNAL_WRITE',
    customerJob: 'PLATFORM_OPERATIONS',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: false,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'provider-credential-lapse',
    name: 'Provider Credential Lapse',
    description:
      'Detects provider credentials expiring within 30 days. Creates a homeowner-visible incident when an already-scheduled booking is at risk, otherwise a provider/admin compliance alert.',
    category: 'RISK_SAFETY',
    schedule: 'Daily at 7:00 AM EST',
    cronExpression: '0 7 * * *',
    type: 'cron',
    triggerSupported: false,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: true,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'provider-missing-credential-sweep',
    name: 'Provider Missing Credential Sweep',
    description:
      'Flags providers who list a service category but never submitted its required credential type.',
    category: 'RISK_SAFETY',
    schedule: 'Sundays at 6:00 AM EST',
    cronExpression: '0 6 * * 0',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'provider-missing-credential-sweep',
    triggerSupported: true,
    impact: 'INTERNAL_WRITE',
    customerJob: 'PLATFORM_OPERATIONS',
    defaultEnabledInBeta: true,
    supportsDryRun: true,
    supportsPropertyScope: false,
    broadSweep: true,
    humanApprovalClass: 'NONE',
  },

  // ── Neighborhood (cron) ───────────────────────────────────────────────────
  {
    key: 'nyc-zap-planning-ingest',
    name: 'NYC ZAP Planning Ingest',
    description:
      'Fetches public NYC Department of City Planning ZAP project lifecycle records for explicitly reviewed pilot counties, normalizes them into canonical Property Intelligence observations, and preserves county-level precision. ' +
      'Requires NYC_ZAP_PILOT_ENABLED plus named review evidence; optional NYC_OPEN_DATA_APP_TOKEN raises Socrata API limits.',
    category: 'NEIGHBORHOOD',
    schedule: 'Daily at 3:35 AM EST; source data is published monthly',
    cronExpression: '35 3 * * *',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'nyc-zap-planning-ingest',
    triggerSupported: true,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: false,
    supportsDryRun: true,
    supportsPropertyScope: false,
    broadSweep: true,
    externalProvider: 'New York City Department of City Planning',
    humanApprovalClass: 'NONE',
  },
  {
    key: 'neighborhood-radar-refresh',
    name: 'Neighborhood Radar Refresh',
    description:
      'Refreshes neighborhood event signals (permits, code violations, sales) and updates impact scores.',
    category: 'NEIGHBORHOOD',
    schedule: 'Sundays at 5:00 AM EST',
    cronExpression: '0 5 * * 0',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'neighborhood-radar-refresh',
    triggerSupported: true,
    impact: 'INTERNAL_WRITE',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: true,
    supportsDryRun: true,
    supportsPropertyScope: true,
    externalProvider: 'Neighborhood intelligence sources',
    humanApprovalClass: 'NONE',
  },
  {
    key: 'neighborhood-change-notifications',
    name: 'Neighborhood Change Notifications',
    description:
      'Alerts homeowners about significant neighborhood events that may impact their property value.',
    category: 'NEIGHBORHOOD',
    schedule: 'Daily at 6:00 AM EST',
    cronExpression: '0 6 * * *',
    type: 'cron',
    triggerSupported: false,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: true,
    humanApprovalClass: 'NONE',
  },

  // ── Financial Market (cron) ───────────────────────────────────────────────
  {
    key: 'mortgage-rate-ingest',
    name: 'Mortgage Rate Ingest',
    description:
      'Fetches the weekly Freddie Mac PMMS 30-year and 15-year fixed mortgage rates from the ' +
      'St. Louis Fed FRED API and stores them as MortgageRateSnapshot records. ' +
      'Requires FRED_API_KEY env var; falls back to MORTGAGE_RATE_30YR_FALLBACK / ' +
      'MORTGAGE_RATE_15YR_FALLBACK if set. Safe to re-run — deduplicates on (source, date).',
    category: 'FINANCIAL_MARKET',
    schedule: 'Thursdays at 5:00 PM EST (after PMMS release)',
    cronExpression: '0 17 * * 4',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'mortgage-rate-ingest',
    triggerSupported: true,
    impact: 'INTERNAL_WRITE',
    customerJob: 'DECIDE',
    defaultEnabledInBeta: true,
    supportsDryRun: true,
    supportsPropertyScope: false,
    externalProvider: 'FRED (St. Louis Fed)',
    humanApprovalClass: 'NONE',
  },
  // ── Home Event Radar (cron) ───────────────────────────────────────────────
  {
    key: 'tax-assessment-ingest',
    name: 'Tax Assessment Ingest',
    description:
      'Fetches reviewed property tax reassessment data from configured Socrata city, county-FIPS, ' +
      'or state sources and queues canonical Radar observations with bounded lifecycle and exact ' +
      'source-run outcomes. The reviewed NYC Bronx Tax Class 1 pilot remains disabled until an ' +
      'allowlisted monitored-property dry run passes acceptance. Override ' +
      'schedule via TAX_ASSESSMENT_INGEST_CRON env var.',
    category: 'RISK_SAFETY',
    schedule: 'Weekly, Mondays at 6:00 AM',
    cronExpression: '0 6 * * 1',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'tax-assessment-ingest',
    triggerSupported: true,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'DECIDE',
    defaultEnabledInBeta: false,
    supportsDryRun: true,
    supportsPropertyScope: true,
    externalProvider: 'NYC Department of Finance and reviewed Socrata portals',
    humanApprovalClass: 'NONE',
  },
  {
    key: 'radar-safety-net-reconciliation',
    name: 'Home Event Radar Safety-Net Reconciliation',
    description:
      'Re-derives incomplete or failed active-event property matches, materializes missing source ' +
      'coverage evaluations, releases bounded Radar dead-letter claims, and expires lifecycle ' +
      'visibility/material-update markers according to reviewed policy. Override schedule via ' +
      'RADAR_SAFETY_NET_RECONCILIATION_CRON.',
    category: 'RISK_SAFETY',
    schedule: 'Hourly at minute 17',
    cronExpression: '17 * * * *',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'radar-safety-net-reconciliation',
    triggerSupported: true,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: true,
    supportsDryRun: true,
    supportsPropertyScope: true,
    broadSweep: true,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'reserve-fund-recalculation',
    name: 'Reserve Fund Recalculation',
    description:
      'Safety-net sweep for the Home Reserve / Sinking Fund Planner. The primary trigger is ' +
      'event-driven (fired when a property\'s Capital Timeline is regenerated); this sweep catches ' +
      'any funds that missed that trigger and recomputes any fund not touched in 35+ days. ' +
      'Override schedule via RESERVE_FUND_SWEEP_CRON env var.',
    category: 'FINANCIAL_MARKET',
    schedule: 'Monthly, 1st at 4:00 AM',
    cronExpression: '0 4 1 * *',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'reserve-fund-recalculation',
    triggerSupported: true,
    impact: 'INTERNAL_WRITE',
    customerJob: 'DECIDE',
    defaultEnabledInBeta: true,
    supportsDryRun: true,
    supportsPropertyScope: true,
    broadSweep: true,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'reserve-fund-reconciliation',
    name: 'Reserve Fund Reconciliation',
    description:
      'Computes fuzzy expense-match suggestions for open Reserve Fund line items and notifies the ' +
      'homeowner when any exist. Suggestions are computed live (not persisted), so this runs weekly ' +
      'rather than daily to avoid re-notifying for the same still-open suggestion too often. ' +
      'Override schedule via RESERVE_FUND_RECONCILIATION_CRON env var.',
    category: 'FINANCIAL_MARKET',
    schedule: 'Sundays at 5:00 AM EST',
    cronExpression: '0 5 * * 0',
    type: 'cron',
    triggerSupported: false,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'DECIDE',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: true,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'reserve-fund-balance-reminder',
    name: 'Reserve Fund Balance Reminder',
    description:
      'Nudges homeowners whose Reserve Fund balance has gone 45+ days without a logged deposit or ' +
      'withdrawal — balances are entirely self-reported (no bank-linking integration exists), so a ' +
      'stale fund silently drifts from reality otherwise.',
    category: 'FINANCIAL_MARKET',
    schedule: 'Monthly, 1st at 9:00 AM EST',
    cronExpression: '0 9 1 * *',
    type: 'cron',
    triggerSupported: false,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'DECIDE',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: true,
    humanApprovalClass: 'NONE',
  },

  // ── Home Intelligence (cron) ──────────────────────────────────────────────
  {
    key: 'home-briefing-delivery',
    name: 'Home Briefing Delivery',
    description:
      'Builds cadence-aware Home Briefing deliveries from eligible canonical Property Changes and Home Actions. ' +
      'Creates zero-to-many items, snapshots source health, and preserves delivery history. Idempotent — safe to re-run. ' +
      'Override schedule via HOME_BRIEFING_DELIVERY_CRON env var.',
    category: 'HOME_INTELLIGENCE',
    schedule: 'Hourly; cadence rules suppress duplicate weekly, monthly, and important-only deliveries',
    cronExpression: '0 * * * *',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'home-briefing-delivery',
    triggerSupported: true,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: true,
    broadSweep: true,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'shared-data-backfill',
    name: 'Shared Data Backfill',
    description:
      'Backfills shared CtC data primitives (PreferenceProfile, AssumptionSet, and Signal) for existing properties. Idempotent and safe to rerun. ' +
      'Disabled by default in beta — the single-environment operating model assumes no real-user migration/backfill requirement (WKR-011).',
    category: 'HOME_INTELLIGENCE',
    schedule: 'Daily at 2:20 AM EST',
    cronExpression: '20 2 * * *',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'shared-data-backfill',
    triggerSupported: true,
    impact: 'INTERNAL_WRITE',
    customerJob: 'PLATFORM_OPERATIONS',
    defaultEnabledInBeta: false,
    supportsDryRun: true,
    supportsPropertyScope: true,
    broadSweep: true,
    humanApprovalClass: 'HIGH_IMPACT_MANUAL',
  },
  {
    key: 'shared-data-consistency-audit',
    name: 'Shared Data Consistency Audit',
    description:
      'Builds shared-data consistency and readiness diagnostics across properties for operational visibility.',
    category: 'HOME_INTELLIGENCE',
    schedule: 'Daily at 2:40 AM EST',
    cronExpression: '40 2 * * *',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'shared-data-consistency-audit',
    triggerSupported: true,
    impact: 'READ_ONLY',
    customerJob: 'PLATFORM_OPERATIONS',
    defaultEnabledInBeta: true,
    supportsDryRun: true,
    supportsPropertyScope: false,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'shared-signal-refresh',
    name: 'Shared Signal Refresh',
    description:
      'Recomputes core shared signals for existing properties with confidence and decay updates. Idempotent and safe to rerun.',
    category: 'HOME_INTELLIGENCE',
    schedule: 'Daily at 2:55 AM EST',
    cronExpression: '55 2 * * *',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'shared-signal-refresh',
    triggerSupported: true,
    impact: 'INTERNAL_WRITE',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: true,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'shared-signal-health-audit',
    name: 'Shared Signal Health Audit',
    description:
      'Builds operational signal-health diagnostics (stale, low-confidence, and interaction signal coverage).',
    category: 'HOME_INTELLIGENCE',
    schedule: 'Daily at 3:10 AM EST',
    cronExpression: '10 3 * * *',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'shared-signal-health-audit',
    triggerSupported: true,
    impact: 'READ_ONLY',
    customerJob: 'PLATFORM_OPERATIONS',
    defaultEnabledInBeta: true,
    supportsDryRun: true,
    supportsPropertyScope: false,
    humanApprovalClass: 'NONE',
  },
  // ── Guidance Engine (cron) ────────────────────────────────────────────────
  {
    key: 'expire-guidance-signals',
    name: 'Expire Guidance Signals',
    description:
      'Archives ACTIVE GuidanceSignal records whose expiresAt timestamp has passed (e.g. freeze-risk signals after the 36-hour weather window).',
    category: 'RISK_SAFETY',
    schedule: 'Daily at 1:30 AM EST',
    cronExpression: '30 1 * * *',
    type: 'cron',
    triggerSupported: false,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: true,
    humanApprovalClass: 'NONE',
  },

  // ── Home Care (cron) ──────────────────────────────────────────────────────
  {
    key: 'home-habit-generation',
    name: 'Home Habit Generation',
    description:
      'Generates personalized home care habits for all properties based on their profile, systems, and season. Deduplicates habits that are already active or snoozed.',
    category: 'HOME_CARE',
    schedule: 'Saturdays at 3:30 AM EST',
    cronExpression: '30 3 * * 6',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'home-habit-generation',
    triggerSupported: true,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: true,
    supportsDryRun: true,
    supportsPropertyScope: true,
    broadSweep: true,
    humanApprovalClass: 'NONE',
  },

  // ── Permit Tracker (cron + BullMQ) ────────────────────────────────────────
  {
    key: 'renovation-advisor-session-expiry',
    name: 'Renovation Advisor Session Expiry',
    description:
      'Archives advisor sessions after their retention deadline so stale evaluations cannot be mutated or re-run.',
    category: 'HOME_INTELLIGENCE',
    schedule: 'Daily at 1:45 AM EST',
    cronExpression: '45 1 * * *',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'renovation-advisor-session-expiry',
    triggerSupported: true,
    impact: 'INTERNAL_WRITE',
    customerJob: 'PLATFORM_OPERATIONS',
    defaultEnabledInBeta: true,
    supportsDryRun: true,
    supportsPropertyScope: true,
    broadSweep: true,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'renovation-permit-requirement-reminders',
    name: 'Renovation Permit Requirement Reminders',
    description:
      'Creates deduplicated, durable notifications for unresolved blocking permit requirements due within three days.',
    category: 'MAINTENANCE',
    schedule: 'Daily at 8:15 AM EST',
    cronExpression: '15 8 * * *',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'renovation-permit-requirement-reminders',
    triggerSupported: true,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: true,
    supportsDryRun: true,
    supportsPropertyScope: true,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'permit-inspection-reminders',
    name: 'Permit Inspection Reminders',
    description:
      'Sends in-app notifications to homeowners for inspection milestones scheduled within the next 3 days that have not yet been notified.',
    category: 'MAINTENANCE',
    schedule: 'Daily at 8:00 AM EST',
    cronExpression: '0 8 * * *',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'permit-inspection-reminders',
    triggerSupported: true,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: true,
    supportsDryRun: true,
    supportsPropertyScope: true,
    humanApprovalClass: 'NONE',
  },

  // ── Savings and Benefits (cron) ────────────────────────────────────────────
  {
    key: 'savings-benefits-deadline-reminders',
    name: 'Savings and Benefits Deadline Reminders',
    description:
      'Sends in-app notifications to homeowners for benefit matches whose program application window closes within 5 days and that have not yet been notified or acted on.',
    category: 'FINANCIAL_MARKET',
    schedule: 'Daily at 8:00 AM EST',
    cronExpression: '0 8 * * *',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'savings-benefits-deadline-reminders',
    triggerSupported: true,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'DECIDE',
    defaultEnabledInBeta: true,
    supportsDryRun: true,
    supportsPropertyScope: true,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'savings-benefits-follow-up-reminders',
    name: 'Savings and Benefits Action Follow-up Reminders',
    description:
      'Reminds opted-in homeowners when a durable Savings and Benefits action reaches its requested follow-up date.',
    category: 'FINANCIAL_MARKET',
    schedule: 'Hourly',
    cronExpression: '15 * * * *',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'savings-benefits-follow-up-reminders',
    triggerSupported: true,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'DECIDE',
    defaultEnabledInBeta: true,
    supportsDryRun: true,
    supportsPropertyScope: true,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'savings-benefits-source-health-audit',
    name: 'Savings and Benefits Source Health Audit',
    description:
      'Evaluates every reviewed source against its configured review SLA and publishes bounded health metrics for operational alerting.',
    category: 'FINANCIAL_MARKET',
    schedule: 'Hourly',
    cronExpression: '0 * * * *',
    type: 'cron',
    queueName: 'cron-trigger-queue',
    jobName: 'savings-benefits-source-health-audit',
    triggerSupported: true,
    impact: 'READ_ONLY',
    customerJob: 'PLATFORM_OPERATIONS',
    defaultEnabledInBeta: true,
    supportsDryRun: true,
    supportsPropertyScope: false,
    broadSweep: true,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'permit-fetch',
    name: 'Permit History Fetch',
    description:
      'Fetches municipal permit history for a property from the configured permit-records provider.',
    category: 'MAINTENANCE',
    schedule: 'On-demand (event-driven)',
    cronExpression: '',
    type: 'bullmq',
    queueName: 'permit-fetch-queue',
    jobName: 'fetch-permit-history',
    triggerSupported: false,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'MAJOR_MOMENT',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: true,
    externalProvider: 'Municipal permit-records provider',
    humanApprovalClass: 'NONE',
  },
  {
    key: 'detect-unpermitted-work',
    name: 'Detect Unpermitted Work',
    description:
      'Cross-references a property\'s inventory/renovation records against its fetched permit history to flag work that appears to lack a matching permit.',
    category: 'MAINTENANCE',
    schedule: 'On-demand (event-driven)',
    cronExpression: '',
    type: 'bullmq',
    queueName: 'detect-unpermitted-work-queue',
    jobName: 'detect-unpermitted-work',
    triggerSupported: false,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'MAJOR_MOMENT',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: true,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'generate-permit-disclosure',
    name: 'Generate Permit Disclosure',
    description:
      'Generates a seller-facing permit disclosure export/report for a property.',
    category: 'MAINTENANCE',
    schedule: 'On-demand (event-driven)',
    cronExpression: '',
    type: 'bullmq',
    queueName: 'generate-permit-disclosure-queue',
    jobName: 'generate-permit-disclosure',
    triggerSupported: false,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'MAJOR_MOMENT',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: true,
    humanApprovalClass: 'NONE',
  },

  // ── DIY Templates (BullMQ, event-driven) ──────────────────────────────────
  {
    key: 'generate-diy-ai-guide',
    name: 'DIY AI Guide Generation',
    description:
      'Generates an AI-authored DIY project guide (materials, steps, safety notes) via Gemini for a homeowner-requested guide.',
    category: 'DIY_TEMPLATES',
    schedule: 'On-demand (event-driven)',
    cronExpression: '',
    type: 'bullmq',
    queueName: 'diy-ai-guide-queue',
    jobName: 'GENERATE_DIY_AI_GUIDE',
    triggerSupported: false,
    impact: 'HOMEOWNER_STATE',
    customerJob: 'MAJOR_MOMENT',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: true,
    externalProvider: 'Gemini',
    humanApprovalClass: 'NONE',
  },
];

// ─── Runner / poller registry ──────────────────────────────────────────────
//
// Long-running pollers under apps/workers/src/runners/ don't have a cron
// expression or BullMQ queue and were previously invisible to both the
// execution-policy gate and the admin Worker Jobs dashboard (WKR-004 /
// audit Section 4.2). Each one is evaluated once at worker startup via
// evaluateWorkerExecution(key, 'poller', policy) before its loop starts.

export interface RunnerRegistryEntry extends WorkerExecutionPolicy {
  key: string;
  name: string;
  description: string;
}

export const RUNNER_REGISTRY: RunnerRegistryEntry[] = [
  {
    key: 'home-report-export-poller',
    name: 'Home Report Export Poller',
    description: 'Claims and processes pending Home Report export jobs.',
    impact: 'HOMEOWNER_STATE',
    customerJob: 'PLATFORM_OPERATIONS',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: true,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'material-spec-export-poller',
    name: 'Material Spec Export Poller',
    description: 'Claims and processes pending material-spec export jobs.',
    impact: 'HOMEOWNER_STATE',
    customerJob: 'PLATFORM_OPERATIONS',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: true,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'report-export-cleanup',
    name: 'Report Export Cleanup',
    description: 'Expires and deletes exported reports past their retention window; reclaims exports stuck in GENERATING.',
    impact: 'DESTRUCTIVE',
    customerJob: 'PLATFORM_OPERATIONS',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: false,
    broadSweep: true,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'material-spec-export-cleanup',
    name: 'Material Spec Export Cleanup',
    description: 'Expires and deletes material-spec exports past their retention window; reclaims exports stuck in GENERATING.',
    impact: 'DESTRUCTIVE',
    customerJob: 'PLATFORM_OPERATIONS',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: false,
    broadSweep: true,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'high-priority-email-enqueue-poller',
    name: 'High-priority Email Enqueue Poller',
    description: 'Enqueues pending high-priority (immediate-delivery) email notifications.',
    impact: 'OUTBOUND',
    customerJob: 'PLATFORM_OPERATIONS',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: false,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'radar-notification-delivery-poller',
    name: 'Home Event Radar Notification Delivery Poller',
    description: 'Dispatches eligible immediate and quiet-hours-deferred Radar email/push delivery rows with durable claims and retries.',
    impact: 'OUTBOUND',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: false,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'domain-events-poller',
    name: 'Domain Events Poller',
    description: 'Processes pending/failed DomainEvent records (claims follow-ups and related cross-cutting effects).',
    impact: 'HOMEOWNER_STATE',
    customerJob: 'PLATFORM_OPERATIONS',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: true,
    humanApprovalClass: 'NONE',
  },
  {
    key: 'claim-follow-up-due-poller',
    name: 'Claim Follow-up Due Poller',
    description: 'Emits idempotent claim follow-up due events.',
    impact: 'HOMEOWNER_STATE',
    customerJob: 'STAY_AHEAD',
    defaultEnabledInBeta: true,
    supportsDryRun: false,
    supportsPropertyScope: true,
    humanApprovalClass: 'NONE',
  },
];
