export const SHARED_SIGNAL_KEYS = [
  'MAINT_ADHERENCE',
  'COVERAGE_GAP',
  'SAVINGS_REALIZATION',
  'RISK_SPIKE',
  'COST_ANOMALY',
  'RISK_ACCUMULATION',
  'SYSTEM_DEGRADATION',
  'COST_PRESSURE_PATTERN',
  'FINANCIAL_DISCIPLINE',
] as const;

export type SharedSignalKey = typeof SHARED_SIGNAL_KEYS[number];
