apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate-homeowner-tables
  namespace: production
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: ghcr.io/madhuboyin/contract-to-cozy/backend:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          # Construct DATABASE_URL with password
          export DATABASE_URL="postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/contracttocozy?schema=public"
          
          cd /app/apps/backend
          
          echo "Current directory: $(pwd)"
          echo "Checking schema file..."
          ls -la prisma/schema.prisma
          
          echo ""
          echo "Running Prisma migration..."
          npx prisma db push --schema=./prisma/schema.prisma --accept-data-loss
          
          EXIT_CODE=$?
          
          if [ $EXIT_CODE -eq 0 ]; then
            echo ""
            echo "Migration successful!"
            echo ""
            echo "Generating Prisma Client..."
            npx prisma generate --schema=./prisma/schema.prisma
          else
            echo ""
            echo "Migration failed with code: $EXIT_CODE"
            exit $EXIT_CODE
          fi
        
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PASSWORD
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
