import type { CompoundRuleDefinition } from './compoundRuleRegistry.contract';

/**
 * Home Intelligence Functional Completeness FRD §15 Phase 5 — populated as
 * each vertical slice/rule from HI-CMP-002 lands. See
 * compoundRuleRegistry.contract.ts for why entries point at a producerId
 * rather than carrying a stored callback.
 */
export const COMPOUND_RULE_REGISTRY: readonly CompoundRuleDefinition[] = [
  {
    ruleId: 'RADAR_COMPOUND_INSIGHT_PROMOTION',
    version: '1.0',
    inputContracts: ['PropertyRadarCompoundInsight'],
    applicability: 'Home Intelligence FRD Phase 5 work item 1 — the first implementation HI-CMP-002 calls for: promote every active Radar compound rule (radarCompoundRules.ts: HEAVY_RAIN_OUTAGE_SUMP_BACKUP, SMOKE_HVAC_FILTER, FREEZE_OUTAGE_ELECTRIC_HEAT, SEVERE_WEATHER_OPEN_ROOF_ISSUE) into a canonical Home Action. These four rules are themselves already instances of HI-CMP-002 rule 2 ("severe weather + unresolved maintenance or vulnerable home system") — see HEAVY_RAIN_UNRESOLVED_GUTTER_DRAINAGE below for that family\'s newest addition.',
    evidenceRequirements: ['Contributing Home Event(s) (matchId, eventType, severity, effectiveAt/expiresAt, source)', 'Contributing property fact(s) (factKey, confirmed/absent/unknown state)'],
    materiality: 'LOW_CONSEQUENCE — advisory awareness, never a material recommendation.',
    safetyTier: 'LOW_CONSEQUENCE',
    outputType: 'HOME_ACTION',
    expirationPolicy: 'Row-driven: the row disappears from the active set (and the projected Home Action with it) as soon as reconcileRadarCompoundInsightsForProperty no longer returns it as active — no separate expiration timer.',
    deduplicationKey: 'PropertyRadarCompoundInsight.correlationKey (sha256 of rule version + property + rule code + sorted constituent match ids)',
    producerId: 'loadCompoundRadarInsightActions',
    recommendedActionBuilder: 'Projects the insight row\'s own reviewed recommendedActionsJson (built by radarCompoundRules.ts per rule) directly into the Home Action\'s recommendedAction text — this producer does not author new recommendation copy.',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
  },
  {
    ruleId: 'INSPECTION_FINDING_WARRANTY_COVERAGE',
    version: '1.0',
    inputContracts: ['InspectionFinding', 'Warranty'],
    applicability: 'HI-CMP-002 rule 1 of 7 — an OPEN, non-informational inspection finding in a confirmed report whose homeSystem is covered (deterministically, by WarrantyCategory) by an active Warranty on the same property. InsurancePolicy correlation is deliberately out of scope for this rule version — see the loader\'s header comment for why.',
    evidenceRequirements: ['The InspectionFinding itself (homeSystem, severity, report confirmation)', 'Every matched active Warranty (category, provider, expiry)'],
    materiality: 'LOW_CONSEQUENCE — advisory ("may be covered, confirm before filing independently"), never asserts the warranty will pay a claim.',
    safetyTier: 'LOW_CONSEQUENCE',
    outputType: 'HOME_ACTION',
    expirationPolicy: 'Live-correlated on every read/recompute — resolves itself automatically once the finding closes, the warranty lapses, or no warranty in that category remains active. No separate persisted state to expire.',
    deduplicationKey: 'inspection-coverage:<InspectionFinding.id> — one insight per finding, aggregating every matching active warranty rather than one row per (finding, warranty) pair.',
    producerId: 'loadInspectionCoverageActions',
    recommendedActionBuilder: 'Names the matched warranty provider(s) and recommends contacting them to check coverage before paying for repairs independently; timing.dueAt is the soonest matching warranty\'s expiry date.',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
  },
  {
    ruleId: 'HEAVY_RAIN_UNRESOLVED_GUTTER_DRAINAGE',
    version: '1.0',
    inputContracts: ['PropertyRadarCompoundInsight (radarCompoundRules.ts rule, HEAVY_RAIN_UNRESOLVED_GUTTER_DRAINAGE)', 'PropertyMaintenanceTask'],
    applicability: 'HI-CMP-002 rule 2 of 7, fifth instance of the family — an active provider-reported heavy_rain or flood_risk event at high/critical/severe/extreme severity, overlapping an OPEN PropertyMaintenanceTask whose title/category text names gutter, downspout, drain(age), or grading work. Extends the roof-issue rule\'s existing pattern to the conventional water-intrusion vulnerability heavy rain exposes; wind/hail are deliberately excluded (those bear on roof structural integrity, a different rule).',
    evidenceRequirements: ['The contributing heavy_rain/flood_risk Home Event (matchId, severity, effectiveAt/expiresAt, source)', 'unresolvedGutterOrDrainageIssue derivation from the open PropertyMaintenanceTask set (radarCompoundInsight.service.ts\'s compoundMaintenanceFacts)'],
    materiality: 'LOW_CONSEQUENCE — advisory awareness, never a material recommendation.',
    safetyTier: 'LOW_CONSEQUENCE',
    outputType: 'HOME_ACTION',
    expirationPolicy: 'Same as RADAR_COMPOUND_INSIGHT_PROMOTION — row-driven, no separate expiration timer; shares its promotion producer.',
    deduplicationKey: 'PropertyRadarCompoundInsight.correlationKey (sha256 of rule version + property + rule code + sorted constituent match ids) — same scheme as the other four Radar rules.',
    producerId: 'loadCompoundRadarInsightActions',
    recommendedActionBuilder: 'Recommends clearing gutters/downspouts and drainage paths, or otherwise routing water away from the foundation, before rain accumulates (radarCompoundRules.ts\'s CLEAR_GUTTERS_AND_DRAINAGE action).',
    sourceFile: 'apps/backend/src/modules/homeEventRadar/domain/radarCompoundRules.ts',
  },
  {
    ruleId: 'PERMIT_ISSUE_ACTIVE_SALE_READINESS',
    version: '1.0',
    inputContracts: ['PropertySaleCase', 'PropertyPermitRecord', 'PermitUnpermittedFlag'],
    applicability: 'HI-CMP-002 rule 3 of 7 — an unverified PropertyPermitRecord or an unresolved PermitUnpermittedFlag, already projected into a SaleReadinessItem by propertySaleCase.service.ts\'s projectPermits(), on a property with an active (not CLOSED/CANCELLED) PropertySaleCase. The compound significance is the sale context itself: an otherwise low-urgency permit-hygiene issue becomes a disclosure-risk/buyer-confidence concern only because a sale is active. Unlike InspectionFinding (which already has its own standalone loadInspectionFindingActions Home Action), no producer promoted permit issues into a Home Action at all before this rule — a genuine, previously uncovered gap, not a duplicate of an existing path.',
    evidenceRequirements: ['The SaleReadinessItem itself (title, detail, category, requirementClass)', 'The active PropertySaleCase (status, target list/close date)'],
    materiality: 'LOW_CONSEQUENCE — advisory ("this may affect buyer confidence, negotiations, or disclosure readiness"), never asserts a legal or transactional consequence.',
    safetyTier: 'LOW_CONSEQUENCE',
    outputType: 'HOME_ACTION',
    expirationPolicy: 'Row-driven: resolves itself once the SaleReadinessItem is no longer OPEN or the sale case closes/cancels — no separate expiration timer.',
    deduplicationKey: 'sale-prep:<SaleReadinessItem.id> — shares loadSalePrepActions\' existing per-item id scheme with SALE_PREP_SELF_REPORT/SALE_PREP_GENERIC.',
    producerId: 'loadSalePrepActions',
    recommendedActionBuilder: 'Reuses loadSalePrepActions\' existing sale-stage-aware framing (PREPARING/LISTED/UNDER_CONTRACT copy) applied generically to the SaleReadinessItem\'s title/detail — no rule-specific copy authored.',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
  },
  {
    ruleId: 'HIGH_PREMIUM_ELIGIBLE_MITIGATION',
    version: '1.0',
    inputContracts: ['RiskPremiumOptimizationAnalysis', 'RiskMitigationPlanItem'],
    applicability: 'HI-CMP-002 rule 4 of 7 — a RECOMMENDED, governance-complete RiskMitigationPlanItem whose targetPeril matches a HIGH-severity entry in the same READY analysis\'s premiumDrivers (MitigationPeril and PremiumDriver.relatedPerils share one taxonomy: WATER/FIRE/WIND_HAIL/THEFT/LIABILITY/ELECTRICAL/OTHER). Both halves were already computed together by one riskPremiumOptimizer.service.ts analysis run, but neither had a Home Action producer before this rule. An untargeted plan item (no targetPeril) is deliberately excluded rather than loosely tied to "some" HIGH driver.',
    evidenceRequirements: ['Every matched HIGH-severity premium driver (code, title, detail)', 'The RECOMMENDED plan item itself (title, why, estimatedCost, carrierReviewQuestion)'],
    materiality: 'LOW_CONSEQUENCE — advisory ("this mitigation may reduce your premium, subject to carrier confirmation"), never asserts a guaranteed discount (carrierBenefitStatus stays UNKNOWN unless a named carrier source is linked).',
    safetyTier: 'LOW_CONSEQUENCE',
    outputType: 'HOME_ACTION',
    expirationPolicy: 'Row-driven: resolves itself once the plan item leaves RECOMMENDED status (PLANNED/COMPLETED/SKIPPED/RESTORED, via riskPremiumOptimizer.service.ts\'s updatePlanItem) or a newer analysis run supersedes it. No separate expiration timer.',
    deduplicationKey: 'mitigation-plan:<RiskMitigationPlanItem.id>',
    producerId: 'loadRiskMitigationActions',
    recommendedActionBuilder: 'Uses the plan item\'s own governed mitigationHandoff() label/href as the primary CTA (imported governance, not re-authored) and cites every matched HIGH-severity driver plus the carrier review question as evidence/why-it-matters text.',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
  },
  {
    ruleId: 'MORTGAGE_COST_CHANGE_REFINANCE_OPPORTUNITY',
    version: '1.0',
    inputContracts: ['OwnershipCostChange', 'PropertyRefinanceRadarState', 'PropertyFinancingProfile'],
    applicability: 'HI-CMP-002 rule 5 of 7 — "property-cost change + refinance or ownership-cost decision threshold." An enrichment, not a new candidate: a material MORTGAGE_PRINCIPAL/MORTGAGE_INTEREST OwnershipCostChange (loadOwnershipCostChangeActions\' existing obligation) is additionally checked against the same refinance-opportunity readiness loadRefinanceOpportunityActions itself requires (OPEN radar state, complete mortgage profile, fresh market/mortgage data, a captured currentOpportunity). When ready, the CTA/evidence/priority are enriched to point at the concrete refinance lever instead of the generic "review financing" destination; id/lineageId/sourceEntityId/decisionLineagePolicy are untouched (HI-ATT-009\'s enrichment contract — same obligation, never a second competing action).',
    evidenceRequirements: ['The OwnershipCostChange observation itself (category, amount delta, comparable-period evidence)', 'The ready refinance opportunity (market rate, monthly savings, break-even months) when one exists'],
    materiality: 'MATERIAL_FINANCIAL — inherits loadOwnershipCostChangeActions\' existing governance; the enrichment adds evidence/routing only, it does not change the safety tier.',
    safetyTier: 'MATERIAL_FINANCIAL',
    outputType: 'HOME_ACTION',
    expirationPolicy: 'Recomputed on every read: the refinance-readiness check re-runs each time loadOwnershipCostChangeActions runs, so enrichment disappears automatically once the opportunity closes, the radar state leaves OPEN, or the mortgage/market data goes stale — no separate expiration timer.',
    deduplicationKey: 'Shares loadOwnershipCostChangeActions\' existing ownership-cost-change:<OwnershipCostChange.id> identity — enrichment never mints a new id.',
    producerId: 'loadOwnershipCostChangeActions',
    recommendedActionBuilder: 'Overrides the primary CTA to "Compare refinance options" -> the Mortgage Refinance Radar tool, and appends a sentence naming the estimated monthly savings and break-even window to whyItMatters — both computed by getReadyMortgageRefinanceOpportunitySummary, not authored per-instance.',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
  },
  {
    ruleId: 'RECURRING_FAILURE_REPAIR_REPLACE_READINESS',
    version: '1.0',
    inputContracts: ['HomeEvent (type REPAIR/MAINTENANCE)', 'ReplaceRepairAnalysis'],
    applicability: 'HI-CMP-002 rule 6 of 7 — "recurring failure + repair-versus-replace decision readiness." An enrichment of loadRepairReplaceDecisionActions\' existing obligation, not a new candidate: two or more HomeEvent rows of type REPAIR/MAINTENANCE against the same inventoryItemId within a 30-month lookback (countRecentRepairEventsByInventoryItem) — the identical convention and window hvacRepairReplaceEngine.service.ts\'s own repairEventCountLast30Months input already uses, recomputed here rather than read off a persisted analysis\'s inputsSnapshot since only the HVAC-specific engine populates that field and this rule must cover every inventory category the generic replaceRepairAnalysis.service.ts also serves. A single past repair is not "recurring."',
    evidenceRequirements: ['Every counted REPAIR/MAINTENANCE HomeEvent (implicitly, via the aggregate count) for the item', 'The READY ReplaceRepairAnalysis itself (verdict, confidence, summary)'],
    materiality: 'MATERIAL_FINANCIAL — inherits loadRepairReplaceDecisionActions\' existing governance and HVAC_REPAIR_REPLACE decision-lineage requirement; the enrichment adds evidence/priority only.',
    safetyTier: 'MATERIAL_FINANCIAL',
    outputType: 'HOME_ACTION',
    expirationPolicy: 'Recomputed on every read: the repair-event count re-runs each time loadRepairReplaceDecisionActions runs, so enrichment disappears automatically once the count ages out of the 30-month window. No separate expiration timer.',
    deduplicationKey: 'Shares loadRepairReplaceDecisionActions\' existing repair-replace:<ReplaceRepairAnalysis.id> identity — enrichment never mints a new id.',
    producerId: 'loadRepairReplaceDecisionActions',
    recommendedActionBuilder: 'Appends a sentence naming the repair/maintenance event count to whyItMatters and elevates priority to SOON when the pattern is recurring — computed by countRecentRepairEventsByInventoryItem, not authored per-instance.',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
  },
  {
    ruleId: 'DOCUMENT_PROMOTED_FACT_CONFLICT',
    version: '1.0',
    inputContracts: ['InsurancePolicyTerm', 'InsurancePolicyFact'],
    applicability: 'HI-CMP-002 rule 7 of 7 — "document-promoted fact + existing conflicting fact." A new HOME_ACTION producer, not an enrichment: every InsurancePolicyTerm document promotion (insurancePolicyRecord.service.ts\'s stageExtractedPolicyTerm, invoked by homeRecordsExtraction.service.ts\'s promoteInsurancePolicy) stages a PENDING_CONFIRMATION term with PENDING facts, with zero comparison against what is already CONFIRMED on file — HI-DOC-004\'s conflict-exposure requirement was implemented nowhere in this pipeline before this rule. A pending fact conflicts when a CONFIRMED fact for the same factKey exists on a different, non-pending term of the same policy with a different value; when multiple confirmed values exist for the same key across terms, the most recent term (by termStart) wins.',
    evidenceRequirements: ['The newly extracted (PENDING) fact value, per HI-DOC-004 never silently discarded', 'The currently CONFIRMED fact value it conflicts with, per HI-DOC-004 never silently discarded'],
    materiality: 'LOW_CONSEQUENCE — advisory data-quality flag ("review and confirm which value is correct"), never asserts which value is right.',
    safetyTier: 'LOW_CONSEQUENCE',
    outputType: 'HOME_ACTION',
    expirationPolicy: 'Recomputed on every read: the conflict check re-runs each time this producer runs, so the action disappears automatically once the pending term is confirmed/rejected (confirmPolicyFact) or the underlying facts otherwise stop disagreeing. No separate expiration timer.',
    deduplicationKey: 'insurance-fact-conflict:<InsurancePolicyTerm.id> — one action per pending term, aggregating every conflicting fact rather than one row per (term, fact) pair.',
    producerId: 'loadInsurancePolicyFactConflictActions',
    recommendedActionBuilder: 'Lists every conflicting fact (label, newly extracted value, currently confirmed value) in whyItMatters and directs the homeowner to review and confirm the correct value — this producer does not resolve the conflict itself, only surfaces it.',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
  },
];
