import type { HomeActionProducerOwnershipEntry } from './homeActionProducerOwnership.contract';

/**
 * Home Intelligence Functional Completeness FRD §15 Phase 0 work item 2 —
 * inventory of every function that produces Home Actions, confirmed by
 * direct code read of homeActionSourcePromotion.service.ts's
 * getPromotedHomeActions() call list, orchestration.service.ts's risk
 * assessment adapter, entryContext.service.ts's activation adapter, and
 * homeActions.service.ts's already-accepted-work re-projection.
 *
 * HomeAction carries no stable producerId field — only source.kind (11
 * values, shared by several distinct producers) and source.entityId (the
 * domain entity's own id, not a producer tag). Some, not all, producers
 * build action.id with a fixed literal prefix; executeHomeActionCommand
 * already exploits two of those prefixes (see OWNERSHIP_COST_CHANGE_ID_PREFIX
 * / ACTIVATION_ID_PREFIX below) to route completion commands past the
 * source-kind-level SOURCE_KINDS_WITHOUT_COMPLETION_ADAPTER guard in
 * homeActionAdapterOwnership.ts. Because no producer identifier is
 * available on the action object itself, this registry is necessarily
 * static/declarative (keyed by loader function name) rather than derived
 * from a live HomeAction — a per-loader schema field is a larger change
 * than Phase 0 scope (see this file's sibling completeness test,
 * homeActionProducerOwnership.test.js, which is what actually catches a
 * new loader added without a row here).
 */

export const OWNERSHIP_COST_CHANGE_ID_PREFIX = 'ownership-cost-change:';
export const ACTIVATION_ID_PREFIX = 'activation:';

export const HOME_ACTION_PRODUCER_OWNERSHIP: readonly HomeActionProducerOwnershipEntry[] = [
  {
    producerId: 'adaptEnvironmentInsightsToHomeActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    sourceKind: 'MAINTENANCE',
    idPrefixes: ['environment:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: true,
    workItemSourceType: 'MAINTENANCE',
    notes: 'ACKNOWLEDGE only.',
  },
  {
    producerId: 'loadGuidanceActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    sourceKind: 'GUIDANCE',
    idPrefixes: [],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: true,
    workItemSourceType: 'GUIDANCE',
    notes: 'ACKNOWLEDGE only. No fixed id prefix.',
  },
  {
    producerId: 'loadIncidentActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    sourceKind: 'INCIDENT',
    idPrefixes: ['incident:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: true,
    workItemSourceType: 'INCIDENT',
    notes: 'ACKNOWLEDGE, plus CORRECT_FACT when critical.',
  },
  {
    producerId: 'loadSeasonalChecklistActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    sourceKind: 'MAINTENANCE',
    idPrefixes: ['seasonal-checklist:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    notes: 'One aggregate action over many checklist items — mapping it to a single work item would be semantically wrong, so it is explicitly excluded from work-item eligibility (isSeasonalAggregate in homeActionWorkItem.adapter.ts) even though the MAINTENANCE kind is otherwise eligible. SNOOZE/NOT_RELEVANT only.',
  },
  {
    producerId: 'loadRecallActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    sourceKind: 'RECALL',
    idPrefixes: ['recall:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: true,
    workItemSourceType: 'RECALL',
    notes: 'ACKNOWLEDGE, plus CORRECT_FACT when critical.',
  },
  {
    producerId: 'loadInspectionFindingActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    sourceKind: 'INSPECTION_FINDING',
    idPrefixes: ['inspection-finding:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    notes: 'ACKNOWLEDGE, plus CORRECT_FACT when safety-relevant. Not yet promoted into a work item — later-phase work.',
  },
  {
    producerId: 'loadCoverageActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    sourceKind: 'COVERAGE',
    idPrefixes: [],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: true,
    workItemSourceType: 'COVERAGE',
    notes: 'ACKNOWLEDGE only. No fixed id prefix.',
  },
  {
    producerId: 'loadCoverageRenewalActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    sourceKind: 'COVERAGE',
    idPrefixes: ['coverage-renewal:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: true,
    workItemSourceType: 'COVERAGE',
    notes: 'ACKNOWLEDGE only. Added Phase 1 Slice 1 (Warranty/InsurancePolicy renewal) — the producer this Phase 0 pass adds a row for after it was missing from the original registry report.',
  },
  {
    producerId: 'loadHealthInsightActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    sourceKind: 'SYSTEM',
    idPrefixes: ['health-insight:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    notes: 'ACKNOWLEDGE only. Added Phase 1 Slice 2 (health-score/appliance install-year gaps) — the producer this Phase 0 pass adds a row for after it was missing from the original registry report.',
  },
  {
    producerId: 'loadRepairReplaceDecisionActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    sourceKind: 'GUIDANCE',
    idPrefixes: ['repair-replace:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: true,
    workItemSourceType: 'GUIDANCE',
    notes: 'ACKNOWLEDGE only. Added Phase 1 Slice 2 (ReplaceRepairAnalysis) — the producer this Phase 0 pass adds a row for after it was missing from the original registry report.',
  },
  {
    producerId: 'loadPersonalizationActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    sourceKind: 'PERSONALIZATION',
    idPrefixes: ['personalization:'],
    hasCompletionAdapter: true,
    completionAdapterOwner: 'applyPersonalizationHomeActionLifecycle (modules/personalization/application/applyHomeActionLifecycle.usecase.ts)',
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    notes: 'The only producer with a real COMPLETE/ALREADY_DONE adapter declared at the source-kind level too — no id-prefix carve-out needed.',
  },
  {
    producerId: 'loadProjectActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    sourceKind: 'PROJECT',
    idPrefixes: ['project:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: true,
    workItemSourceType: 'PROJECT',
    notes: 'ACKNOWLEDGE only.',
  },
  {
    producerId: 'loadSalePrepActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    sourceKind: 'SALE_PREP',
    idPrefixes: [],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: true,
    workItemSourceType: 'SALE_PREP',
    notes: 'Completion happens by the homeowner updating the self-reported condition on Sale Case, not a COMPLETE command against the promoted work item. Id is per-item with an "industry-guidance" suffix, not one fixed literal prefix.',
  },
  {
    producerId: 'loadRefinanceDataRequiredActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    sourceKind: 'SYSTEM',
    idPrefixes: ['refinance-data-required:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    notes: 'ACKNOWLEDGE, plus a NO_MORTGAGE command handled directly by exact-id match in executeHomeActionCommand (markPropertyAsHavingNoMortgage).',
  },
  {
    producerId: 'loadRefinanceOpportunityActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    sourceKind: 'SYSTEM',
    idPrefixes: [],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    notes: 'ACKNOWLEDGE only. Id scheme varies per case (refinance-decision-review or a window id) rather than one fixed prefix.',
  },
  {
    producerId: 'loadHomeDigitalTwinFactReviewActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    sourceKind: 'SYSTEM',
    idPrefixes: ['home-digital-twin-fact-review:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    notes: 'DISMISS/SNOOZE/NOT_RELEVANT/CORRECT_FACT.',
  },
  {
    producerId: 'loadHomeCapitalTimelineMaterialWindowActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    sourceKind: 'SYSTEM',
    idPrefixes: [],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    notes: 'DISMISS/SNOOZE/NOT_RELEVANT/CORRECT_FACT. Own id scheme keyed off recommendationVersion, not a fixed literal prefix.',
  },
  {
    producerId: 'loadPropertyTaxAppealCaseActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    sourceKind: 'SYSTEM',
    idPrefixes: ['property-tax-appeal-case:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    notes: 'SNOOZE/DISMISS/NOT_RELEVANT.',
  },
  {
    producerId: 'loadSavingsBenefitsActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    sourceKind: 'SAVINGS_BENEFITS',
    idPrefixes: ['savings-benefit-action:', 'savings-benefit-match:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    notes: 'Two id-prefixed sub-shapes: "action" (SNOOZE/DEFER/DISMISS/NOT_RELEVANT) and "match" (ACKNOWLEDGE only).',
  },
  {
    producerId: 'loadOwnershipCostChangeActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    sourceKind: 'SYSTEM',
    idPrefixes: [OWNERSHIP_COST_CHANGE_ID_PREFIX],
    hasCompletionAdapter: true,
    completionAdapterOwner: 'ownershipCostDecisionService.record (services/ownershipCosts/ownershipCostDecision.service.ts), routed by id prefix in executeHomeActionCommand (homeActions.service.ts)',
    isKindLevelCompletionException: true,
    workKeyEligible: false,
    workItemSourceType: null,
    notes: 'COMPLETE/ALREADY_DONE supported despite the SYSTEM source kind having no completion adapter at the kind level — this is one of the two id-prefix carve-outs executeHomeActionCommand checks explicitly (see OWNERSHIP_COST_CHANGE_ID_PREFIX above), now declared here instead of being an undeclared exception.',
  },
  {
    producerId: 'adaptOrchestratedActionToHomeAction',
    sourceFile: 'apps/backend/src/services/orchestration.service.ts',
    sourceKind: null,
    idPrefixes: [],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    notes: 'Risk-assessment adapter. Computes source.kind per action (MAINTENANCE/COVERAGE/SYSTEM) from action.source/relatedEntity rather than emitting one fixed kind, and builds id from the raw action.actionKey with no producer prefix — the least identity-stable producer in the feed. ACKNOWLEDGE only.',
  },
  {
    producerId: 'getActivationFirstValue',
    sourceFile: 'apps/backend/src/services/entryContext.service.ts',
    sourceKind: null,
    idPrefixes: [ACTIVATION_ID_PREFIX],
    hasCompletionAdapter: true,
    completionAdapterOwner: 'recordFirstActionResolution (services/entryContext.service.ts), routed by id prefix in executeHomeActionCommand (homeActions.service.ts)',
    isKindLevelCompletionException: true,
    workKeyEligible: false,
    workItemSourceType: null,
    notes: 'Activation/first-value producer. source.kind is resolved dynamically per trigger type by sourceAdapterForTrigger (entryContext.service.ts) — can be MAINTENANCE, COVERAGE, INCIDENT, PROJECT, SYSTEM, or GUIDANCE. This is the other id-prefix carve-out executeHomeActionCommand checks explicitly (see ACTIVATION_ID_PREFIX above), now declared here instead of being an undeclared exception. isKindLevelCompletionException is still meaningful here even though sourceKind is null: whichever dynamic kind is resolved at runtime, none of them declare a kind-level completion adapter, so the exception always applies.',
  },
  {
    producerId: 'appendAcceptedOperationalWork',
    sourceFile: 'apps/backend/src/services/homeActions.service.ts',
    sourceKind: null,
    idPrefixes: ['operational-work:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    notes: 'Re-projects already-ACCEPTED OperationalWorkItem rows back into the feed with source.kind computed from the item\'s primary execution type (PROJECT/GUIDANCE/MAINTENANCE). Never routes through proposeWorkItemFromHomeAction — it already carries an existing work item reference, so workKeyEligible is not applicable rather than a real "no."',
  },
] as const;
