import type { HomeActionProducerOwnershipEntry } from './homeActionProducerOwnership.contract';

/**
 * Home Intelligence Functional Completeness FRD §15 Phase 0 work item 2 —
 * inventory of every function that produces Home Actions, confirmed by
 * direct code read of homeActionSourcePromotion.service.ts's
 * getPromotedHomeActions() call list, orchestration.service.ts's risk
 * assessment adapter, entryContext.service.ts's activation adapter, and
 * homeActions.service.ts's already-accepted-work re-projection.
 *
 * HomeAction carries no stable producerId field — only source.kind (11
 * values, shared by several distinct producers) and source.entityId (the
 * domain entity's own id, not a producer tag). Some, not all, producers
 * build action.id with a fixed literal prefix; executeHomeActionCommand
 * already exploits two of those prefixes (see OWNERSHIP_COST_CHANGE_ID_PREFIX
 * / ACTIVATION_ID_PREFIX below) to route completion commands past the
 * source-kind-level SOURCE_KINDS_WITHOUT_COMPLETION_ADAPTER guard in
 * homeActionAdapterOwnership.ts. Because no producer identifier is
 * available on the action object itself, this registry is necessarily
 * static/declarative (keyed by loader function name) rather than derived
 * from a live HomeAction — a per-loader schema field is a larger change
 * than Phase 0 scope (see this file's sibling completeness test,
 * homeActionProducerOwnership.test.js, which is what actually catches a
 * new loader added without a row here).
 *
 * commandOwner note: unless stated otherwise, "generic default" below means
 * executeHomeActionCommand's fallback path (homeActions.service.ts) —
 * snoozeAction for DEFER/SNOOZE, recordOrchestrationEvent for every other
 * command — which runs for every producer that has no producer-specific
 * branch. Every workKeyEligible producer additionally gets the shared
 * snoozeWorkItem/transitionWorkItem side effects applied against
 * action.workItem before whichever commandOwner below runs; that shared
 * step is declared once here rather than repeated in every entry.
 */

export const OWNERSHIP_COST_CHANGE_ID_PREFIX = 'ownership-cost-change:';
export const ACTIVATION_ID_PREFIX = 'activation:';
// Home Intelligence Functional Completeness FRD Phase 4 — the third
// id-prefix carve-out: appendAcceptedOperationalWork's re-projected accepted
// work now supports COMPLETE/ALREADY_DONE for a maintenance-backed item
// despite its computed source.kind (MAINTENANCE/GUIDANCE/PROJECT) having no
// completion adapter at the kind level.
export const OPERATIONAL_WORK_ID_PREFIX = 'operational-work:';

const GENERIC_DEFAULT_COMMAND_OWNER = 'Generic default (executeHomeActionCommand, services/homeActions.service.ts): snoozeAction for DEFER/SNOOZE, recordOrchestrationEvent otherwise.';

export const HOME_ACTION_PRODUCER_OWNERSHIP: readonly HomeActionProducerOwnershipEntry[] = [
  {
    producerId: 'adaptEnvironmentInsightsToHomeActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'EnvironmentInsight[] — passed in by the caller (already-fetched weather/environment API results), not a direct DB query inside this adapter.',
    sourceKind: 'MAINTENANCE',
    idPrefixes: ['environment:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: true,
    workItemSourceType: 'MAINTENANCE',
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    decisionLineagePolicy: { kind: 'NOT_REQUIRED' },
    notes: 'ACKNOWLEDGE only. Governance is always lowConsequenceGovernance(\'environment-v1\') — never material, so decision lineage never applies.',
  },
  {
    producerId: 'loadGuidanceActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'ProjectRecord + GuidanceJourney (prisma.projectRecord.findMany with its guidance journey/step include).',
    sourceKind: 'GUIDANCE',
    idPrefixes: [],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: true,
    workItemSourceType: 'GUIDANCE',
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    endToEndOutcomeAdapters: [{
      owner: 'recordOperationalWorkOutcome (services/decisionPlatform/outcomeObservationService.ts)',
      completionPath: 'runJourneyCompletionHooks → syncGuidanceWorkItemsOnCompletion (services/guidanceEngine/guidanceCompletionHooks.service.ts)',
      conditions: 'A linked Guidance Operational Work Item exists and authoritative journey completion advances it to VERIFIED.',
    }],
    decisionLineagePolicy: {
      kind: 'VARIES_BY_INSTANCE',
      rationale: 'guidanceGovernance() parses each step\'s own governanceJson (guidanceDefinition author-declared), so safetyTier can be anything -- LOW_CONSEQUENCE, SAFETY_EMERGENCY, MATERIAL_FINANCIAL, or REGULATED_COVERAGE. A material instance is a genuine decision (guidanceDecisionContract already builds assumptions/options/tradeoffs for it) but no decision-family engine covers general guidance journeys today, only the separate repair-replace producer -- resolved per-action by resolveActionDecisionLineagePolicy.',
    },
    notes: 'ACKNOWLEDGE only via executeHomeActionCommand (the command path has no completion or outcome adapter). No fixed id prefix; authoritative journey completion owns the separate end-to-end outcome path declared above.',
  },
  {
    producerId: 'loadIncidentActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'Incident (prisma.incident.findMany).',
    sourceKind: 'INCIDENT',
    idPrefixes: ['incident:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: true,
    workItemSourceType: 'INCIDENT',
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    endToEndOutcomeAdapters: [{
      owner: 'recordOperationalWorkOutcome (services/decisionPlatform/outcomeObservationService.ts)',
      completionPath: 'syncIncidentWorkItem (services/incidents/incidentWorkReconciliation.service.ts)',
      conditions: 'An Incident-linked Operational Work Item exists and the Incident reaches RESOLVED or MITIGATED, advancing the item to VERIFIED.',
    }],
    decisionLineagePolicy: { kind: 'NOT_REQUIRED' },
    notes: 'ACKNOWLEDGE, plus CORRECT_FACT when critical (critical incidents restrict feedbackControls to [\'ACKNOWLEDGE\', \'CORRECT_FACT\'], a subset of the full set shown here). Governance is LOW_CONSEQUENCE or, when critical, SAFETY_EMERGENCY -- never material, so decision lineage never applies (an emergency should not wait on a Decision Thread).',
  },
  {
    producerId: 'loadSeasonalChecklistActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'SeasonalChecklist (prisma.seasonalChecklist.findMany).',
    sourceKind: 'MAINTENANCE',
    idPrefixes: ['seasonal-checklist:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['SNOOZE', 'NOT_RELEVANT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    decisionLineagePolicy: { kind: 'NOT_REQUIRED' },
    notes: 'One aggregate action over many checklist items — mapping it to a single work item would be semantically wrong, so it is explicitly excluded from work-item eligibility (isSeasonalAggregate in homeActionWorkItem.adapter.ts) even though the MAINTENANCE kind is otherwise eligible. SNOOZE/NOT_RELEVANT only. Governance is always lowConsequenceGovernance(\'phase2-seasonal-v1\') — never material.',
  },
  {
    producerId: 'loadRecallActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'RecallMatch (prisma.recallMatch.findMany).',
    sourceKind: 'RECALL',
    idPrefixes: ['recall:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: true,
    workItemSourceType: 'RECALL',
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    decisionLineagePolicy: { kind: 'NOT_REQUIRED' },
    notes: 'ACKNOWLEDGE, plus CORRECT_FACT when critical (same subset relationship as loadIncidentActions). Governance is LOW_CONSEQUENCE or, when critical, SAFETY_EMERGENCY — never material, so decision lineage never applies.',
  },
  {
    producerId: 'loadInspectionFindingActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'InspectionFinding (prisma.inspectionFinding.findMany).',
    sourceKind: 'INSPECTION_FINDING',
    idPrefixes: ['inspection-finding:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    endToEndOutcomeAdapters: [{
      owner: 'recordOperationalWorkOutcome (services/decisionPlatform/outcomeObservationService.ts)',
      completionPath: 'propagateResolutionToFinding (modules/homeOperations/adapters/inspectionFinding.adapter.ts)',
      conditions: 'A separately execution-linked finding Operational Work Item reaches VERIFIED; loadInspectionFindingActions itself remains non-work-item-eligible.',
    }],
    decisionLineagePolicy: {
      kind: 'VARIES_BY_INSTANCE',
      rationale: 'A finding is LOW_CONSEQUENCE, SAFETY_EMERGENCY (isSafety), or MATERIAL_FINANCIAL (isMaterialMajor: MAJOR severity at/above the $1,500 cost threshold) depending on the specific finding. No decision-family engine covers inspection findings yet, so a material instance always fails closed today -- resolved per-action by resolveActionDecisionLineagePolicy.',
    },
    notes: 'ACKNOWLEDGE, plus CORRECT_FACT when safety-relevant (same subset relationship as loadIncidentActions). Not yet promoted into a work item — later-phase work.',
  },
  {
    producerId: 'loadInspectionCoverageActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'InspectionFinding + Warranty (prisma.inspectionFinding.findMany joined live against prisma.warranty.findMany by WarrantyCategory-to-homeSystem mapping) — both canonical records, correlated at read time rather than a persisted second copy.',
    sourceKind: 'SYSTEM',
    idPrefixes: ['inspection-coverage:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    decisionLineagePolicy: { kind: 'NOT_REQUIRED' },
    notes: 'Home Intelligence FRD Phase 5 work item 2, rule 1 of 7 (HI-CMP-002) — inspection finding + applicable warranty evidence. ACKNOWLEDGE only; advisory, never material. Distinct obligation from loadInspectionFindingActions (coverage-checking advice, not finding review) so the two never compete for the same id.',
  },
  {
    producerId: 'loadCoverageActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'CoverageReview (prisma.coverageReview.findMany).',
    sourceKind: 'COVERAGE',
    idPrefixes: [],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: true,
    workItemSourceType: 'COVERAGE',
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    endToEndOutcomeAdapters: [{
      owner: 'recordOperationalWorkOutcome (services/decisionPlatform/outcomeObservationService.ts)',
      completionPath: 'approveMaterialWorkHandler / completeWorkItemHandler (modules/homeOperations/api/homeOperations.controller.ts), or booking completion reconciliation',
      conditions: 'A Coverage recommendation has a linked Operational Work Item and an evidence-governed completion path advances it to VERIFIED.',
    }],
    decisionLineagePolicy: { kind: 'DECISION_REQUIRED', decisionDefinitionId: 'COVERAGE_QUESTION' },
    notes: 'ACKNOWLEDGE only. No fixed id prefix (lineageId is `coverage-review:${questionKey}`). Governance is always fixed MATERIAL_FINANCIAL (a coverage question already carries real options/tradeoffs). Phase 3 review finding 4 delivery step 6: coverageQuestionDecisionFamilyAdapter (domainSnapshotAdapters.ts) wraps the primary open CoverageReviewQuestion.',
  },
  {
    producerId: 'loadCoverageRenewalActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'Warranty + InsurancePolicy (prisma.warranty.findMany, prisma.insurancePolicy.findMany).',
    sourceKind: 'COVERAGE',
    idPrefixes: ['coverage-renewal:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: true,
    workItemSourceType: 'COVERAGE',
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    decisionLineagePolicy: { kind: 'NOT_REQUIRED' },
    notes: 'ACKNOWLEDGE only. Added Phase 1 Slice 1 (Warranty/InsurancePolicy renewal). Phase 3 review finding 4 delivery step 6 reclassification: this is an expiry-date reminder against a static renew-vs-shop choice, not a verdict-bearing recommendation — there is no authoritative evaluation to snapshot (unlike coverage-review\'s CoverageReviewQuestion). Revisit if a real renewal-evaluation engine is ever built for this domain.',
  },
  {
    producerId: 'loadRiskMitigationActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'RiskPremiumOptimizationAnalysis + its RiskMitigationPlanItem relation (prisma.riskPremiumOptimizationAnalysis.findFirst with a planItems include) — a computed analysis run, not one single domain record.',
    sourceKind: 'COVERAGE',
    idPrefixes: ['mitigation-plan:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    decisionLineagePolicy: { kind: 'NOT_REQUIRED' },
    notes: 'Home Intelligence FRD Phase 5 work item 2, rule 4 of 7 (HI-CMP-002) — high premium driver + eligible mitigation plan item. ACKNOWLEDGE only; deliberately not workKeyEligible despite the COVERAGE kind default (loadCoverageRenewalActions is) — the plan item\'s own RECOMMENDED/PLANNED/COMPLETED/SKIPPED lifecycle is already owned by riskPremiumOptimizer.service.ts\'s updatePlanItem, and no Operational Work Item work-key resolver exists for a RiskMitigationPlanItem id; declaring eligibility without one would silently mismatch on acceptance.',
  },
  {
    producerId: 'loadInsurancePolicyFactConflictActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'InsurancePolicyTerm + its InsurancePolicyFact relation (prisma.insurancePolicyTerm.findMany with a facts include, status PENDING_CONFIRMATION) cross-checked against confirmed InsurancePolicyFact rows on other terms of the same policy.',
    sourceKind: 'SYSTEM',
    idPrefixes: ['insurance-fact-conflict:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    decisionLineagePolicy: { kind: 'NOT_REQUIRED' },
    notes: 'Home Intelligence FRD Phase 5 work item 2, rule 7 of 7 (HI-CMP-002) — document-promoted fact + existing conflicting fact. ACKNOWLEDGE/CORRECT_FACT only; advisory data-quality flag, not a material recommendation. Confirming/rejecting the conflicting extraction itself happens through confirmPolicyFact (insurancePolicyRecord.service.ts), not a Home Action command — this producer surfaces the conflict, it does not own resolving it.',
  },
  {
    producerId: 'loadWarrantyConflictActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'Warranty (prisma.warranty.findMany, active only) grouped by category — live-correlated, not read from a persisted conflict record.',
    sourceKind: 'SYSTEM',
    idPrefixes: ['warranty-conflict:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    decisionLineagePolicy: { kind: 'NOT_REQUIRED' },
    notes: 'Home Intelligence FRD Phase 5 work item 6 (HI-DOC-004) — extends rule 7\'s conflict-surfacing pattern from InsurancePolicy to Warranty: two or more active warranties in the same non-OTHER category with a different provider or expiry dates spread more than 30 days apart. ACKNOWLEDGE/CORRECT_FACT only; advisory data-quality flag. CTA routes to /dashboard/warranties, the same correction path Property Context\'s own factCatalog.ts registers for coverage.warranties.',
  },
  {
    producerId: 'loadExpenseDuplicateActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'Expense (prisma.expense.findMany) grouped by matching amount within a short transactionDate window — live-correlated, not read from a persisted conflict record.',
    sourceKind: 'SYSTEM',
    idPrefixes: ['expense-duplicate:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    decisionLineagePolicy: { kind: 'NOT_REQUIRED' },
    notes: 'Home Intelligence FRD Phase 5 work item 6 (HI-DOC-004) — the Expense-side counterpart to loadWarrantyConflictActions, deliberately scoped differently: expenses are discrete transactions where repeats in one category are normal, so this flags likely duplicate entries (same amount within 3 days) rather than "conflicting" records. ACKNOWLEDGE/CORRECT_FACT only; advisory.',
  },
  {
    producerId: 'loadHealthInsightActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'Property + InventoryItem + Warranty (prisma.property.findUnique with inventoryItems/warranties include) — a computed health score, not one single domain record.',
    sourceKind: 'SYSTEM',
    idPrefixes: ['health-insight:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    decisionLineagePolicy: { kind: 'NOT_REQUIRED' },
    notes: 'ACKNOWLEDGE only. Added Phase 1 Slice 2 (health-score/appliance install-year gaps) — the producer this Phase 0 pass adds a row for after it was missing from the original registry report. Governance is always lowConsequenceGovernance(\'resolution-center-parity-v1\') — never material.',
  },
  {
    producerId: 'loadCompoundRadarInsightActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'PropertyRadarCompoundInsight (prisma.propertyRadarCompoundInsight.findMany, status: active) — reconciled upstream by reconcileRadarCompoundInsightsForProperty (the compound-radar intelligence consumer), not queried fresh here.',
    sourceKind: 'SYSTEM',
    idPrefixes: ['compound-radar:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    decisionLineagePolicy: { kind: 'NOT_REQUIRED' },
    notes: 'Home Intelligence FRD Phase 5 work item 1 (HI-CMP-002 vertical slice) — first cross-domain compound rule promoted to a canonical Home Action. ACKNOWLEDGE only; never material. A resolved insight simply stops being emitted (HI-CMP-005 convergence) rather than requiring a homeowner dismissal.',
  },
  {
    producerId: 'loadRepairReplaceDecisionActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'ReplaceRepairAnalysis (prisma.replaceRepairAnalysis.findMany).',
    sourceKind: 'GUIDANCE',
    idPrefixes: ['repair-replace:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: true,
    workItemSourceType: 'GUIDANCE',
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    endToEndOutcomeAdapters: [{
      owner: 'recordOperationalWorkOutcome (services/decisionPlatform/outcomeObservationService.ts)',
      completionPath: 'Guidance/project/booking reconciliation for the related repair-replace journey',
      conditions: 'The analysis is linked through its related Guidance Journey to an Operational Work Item that reaches VERIFIED.',
    }],
    decisionLineagePolicy: { kind: 'DECISION_REQUIRED', decisionDefinitionId: 'HVAC_REPAIR_REPLACE' },
    notes: 'ACKNOWLEDGE only. Added Phase 1 Slice 2 (ReplaceRepairAnalysis) — the producer this Phase 0 pass adds a row for after it was missing from the original registry report. Governance is always fixed MATERIAL_FINANCIAL. The one producer with a real registered decision family (Phase 3A) — resolveActionDecisionLineagePolicy still fails closed per-item when the underlying InventoryItem is not actually HVAC (composeHvacDecisionContext\'s own eligibility gate). Home Intelligence FRD Phase 5 work item 2, rule 6 of 7 (HI-CMP-002): also batch-checks HomeEvent REPAIR/MAINTENANCE history per inventoryItemId (countRecentRepairEventsByInventoryItem, 30-month lookback, 2+ events) and enriches priority/evidence/whyItMatters when a recurring-failure pattern exists — id/lineageId/decisionLineagePolicy are unaffected.',
  },
  {
    producerId: 'loadPersonalizationActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'PersonalizedRecommendation (prisma.personalizedRecommendation.findMany).',
    sourceKind: 'PERSONALIZATION',
    idPrefixes: ['personalization:'],
    hasCompletionAdapter: true,
    completionAdapterOwner: 'applyPersonalizationHomeActionLifecycle (modules/personalization/application/applyHomeActionLifecycle.usecase.ts)',
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['COMPLETE', 'DEFER', 'SNOOZE', 'DISMISS', 'ALREADY_DONE', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: 'applyPersonalizationHomeActionLifecycle (modules/personalization/application/applyHomeActionLifecycle.usecase.ts), routed by source.kind === PERSONALIZATION in executeHomeActionCommand.',
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    decisionLineagePolicy: {
      kind: 'VARIES_BY_INSTANCE',
      rationale: 'safetyTier comes straight from PersonalizedRecommendationDefinition.governance.safetyTier, a reviewed but per-definition DB field — any tier is possible across the personalization catalog. No decision-family engine covers personalization recommendations, so a material instance always fails closed today -- resolved per-action by resolveActionDecisionLineagePolicy.',
    },
    notes: 'The only producer with a real COMPLETE/ALREADY_DONE adapter declared at the source-kind level too — no id-prefix carve-out needed. (Safety-tier recommendations restrict feedbackControls to [\'COMPLETE\', \'ALREADY_DONE\', \'CORRECT_FACT\'], a subset of the full set shown here.)',
  },
  {
    producerId: 'loadProjectActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'ProjectRecord (prisma.projectRecord.findMany).',
    sourceKind: 'PROJECT',
    idPrefixes: ['project:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: true,
    workItemSourceType: 'PROJECT',
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    endToEndOutcomeAdapters: [{
      owner: 'recordOperationalWorkOutcome (services/decisionPlatform/outcomeObservationService.ts)',
      completionPath: 'syncJourneyWorkItemForProjectEvent / syncProjectExecutionWorkItemOnCompletion (services/projectWorkItemReconciliation.service.ts)',
      conditions: 'A linked Project Operational Work Item reaches VERIFIED after authoritative project completion.',
    }],
    decisionLineagePolicy: {
      kind: 'VARIES_BY_INSTANCE',
      rationale: 'projectGovernance() computes SAFETY_EMERGENCY (open safety issue), REGULATED_COVERAGE (coverage-funded), MATERIAL_FINANCIAL (contract amount/permit/HOA/credential/complexity signals), or LOW_CONSEQUENCE per project. No decision-family engine covers projects, so a material instance always fails closed today -- resolved per-action by resolveActionDecisionLineagePolicy.',
    },
    notes: 'ACKNOWLEDGE only via executeHomeActionCommand; the command path has no completion or outcome adapter. Authoritative project completion owns the separate end-to-end outcome path declared above.',
  },
  {
    producerId: 'loadSalePrepActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'PropertySaleCase (prisma.propertySaleCase.findUnique) + SaleReadinessItem (prisma.saleReadinessItem.findMany, filtered to SALE_PREP_SELF_REPORT/SALE_PREP_GENERIC/PERMIT/PERMIT_UNPERMITTED_FLAG source types).',
    sourceKind: 'SALE_PREP',
    idPrefixes: [],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: true,
    workItemSourceType: 'SALE_PREP',
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    endToEndOutcomeAdapters: [{
      owner: 'recordOperationalWorkOutcome (services/decisionPlatform/outcomeObservationService.ts)',
      completionPath: 'syncSaleReadinessItemWorkItem (services/saleReadinessWorkReconciliation.service.ts)',
      conditions: 'A linked Sale Readiness Operational Work Item exists and the homeowner resolves the authoritative SaleReadinessItem, advancing the item to VERIFIED.',
    }],
    decisionLineagePolicy: { kind: 'NOT_REQUIRED' },
    notes: 'Completion happens by the homeowner updating the self-reported condition on Sale Case, not a COMPLETE command against the promoted work item. Id is per-item with an "industry-guidance" suffix, not one fixed literal prefix. Governance is always lowConsequenceGovernance(\'sale-prep-v1\') — never material. Home Intelligence FRD Phase 5 work item 2, rule 3 of 7 (HI-CMP-002) added PERMIT/PERMIT_UNPERMITTED_FLAG to the promotable source types.',
  },
  {
    producerId: 'loadRefinanceDataRequiredActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'DomainEvent (prisma.domainEvent.findFirst).',
    sourceKind: 'SYSTEM',
    idPrefixes: ['refinance-data-required:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'NO_MORTGAGE', 'CORRECT_FACT'],
    commandOwner: 'markPropertyAsHavingNoMortgage (services/homeActions.service.ts) for the exact-id NO_MORTGAGE command only, by exact string match (not an id-prefix check) in executeHomeActionCommand; every other command falls through to the generic default.',
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    decisionLineagePolicy: { kind: 'CONTEXT_CAPTURE_ONLY' },
    notes: 'ACKNOWLEDGE, plus a NO_MORTGAGE command handled directly by exact-id match in executeHomeActionCommand (markPropertyAsHavingNoMortgage). Note: NO_MORTGAGE does not short-circuit — the generic default handler still runs afterward for this command too. Governance is always lowConsequenceGovernance(\'refinance-data-required-v1\'); this is literally "add missing mortgage details," not yet a recommendation.',
  },
  {
    producerId: 'loadRefinanceOpportunityActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'PropertyRefinanceRadarState (prisma.propertyRefinanceRadarState.findUnique).',
    sourceKind: 'SYSTEM',
    idPrefixes: [],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    decisionLineagePolicy: { kind: 'DECISION_REQUIRED', decisionDefinitionId: 'REFINANCE_OPPORTUNITY' },
    notes: 'ACKNOWLEDGE only. Id scheme varies per case (refinance-decision-review or a window id) rather than one fixed prefix, but lineageId is always `refinance-opportunity:${propertyId}`. Governance is always fixed MATERIAL_FINANCIAL. Phase 3 review finding 4 delivery step 6: refinanceOpportunityDecisionFamilyAdapter (domainSnapshotAdapters.ts) wraps PropertyRefinanceRadarState.currentOpportunity.',
  },
  {
    producerId: 'loadHomeDigitalTwinFactReviewActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'HomeDigitalTwin (prisma.homeDigitalTwin.findUnique).',
    sourceKind: 'SYSTEM',
    idPrefixes: ['home-digital-twin-fact-review:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['DISMISS', 'SNOOZE', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    decisionLineagePolicy: { kind: 'CONTEXT_CAPTURE_ONLY' },
    notes: 'DISMISS/SNOOZE/NOT_RELEVANT/CORRECT_FACT. Governance is always lowConsequenceGovernance(\'home-digital-twin-fact-review-v1\') — a fact-review prompt, not a recommendation.',
  },
  {
    producerId: 'loadHomeCapitalTimelineMaterialWindowActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'HomeCapitalTimelineAnalysis (prisma.homeCapitalTimelineAnalysis.findFirst).',
    sourceKind: 'SYSTEM',
    idPrefixes: [],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['DISMISS', 'SNOOZE', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    decisionLineagePolicy: { kind: 'DECISION_REQUIRED', decisionDefinitionId: 'HOME_CAPITAL_TIMELINE_WINDOW' },
    notes: 'DISMISS/SNOOZE/NOT_RELEVANT/CORRECT_FACT. Own id scheme keyed off recommendationVersion, but lineageId is always `home-capital-timeline-window:${item.id}`. Governance is always fixed MATERIAL_FINANCIAL. Phase 3 review finding 4 delivery step 6: homeCapitalTimelineWindowDecisionFamilyAdapter (domainSnapshotAdapters.ts) wraps a single HIGH-priority HomeCapitalTimelineItem.',
  },
  {
    producerId: 'loadSellHoldRentActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'SellHoldRentAnalysis (prisma.sellHoldRentAnalysis.findFirst) — persisted by sellHoldRent.service.ts on every canonical (non-scenario) estimate.',
    sourceKind: 'SYSTEM',
    idPrefixes: ['sell-hold-rent:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    decisionLineagePolicy: { kind: 'DECISION_REQUIRED', decisionDefinitionId: 'SELL_HOLD_RENT' },
    notes: 'DEFER/SNOOZE/DISMISS/NOT_RELEVANT. Governance is always fixed MATERIAL_FINANCIAL. Home Intelligence Functional Completeness FRD Phase 3 review finding 4, delivery step 7: previously no persistence and no producer existed for this domain at all (SellHoldRentService.estimate() computed entirely in-memory) — both were added, plus sellHoldRentDecisionFamilyAdapter (domainSnapshotAdapters.ts) wrapping the latest canonical SellHoldRentAnalysis, one per property.',
  },
  {
    producerId: 'loadPropertyTaxAppealCaseActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'PropertyTaxAppealCase (prisma.propertyTaxAppealCase.findFirst).',
    sourceKind: 'SYSTEM',
    idPrefixes: ['property-tax-appeal-case:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['SNOOZE', 'DISMISS', 'NOT_RELEVANT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    decisionLineagePolicy: { kind: 'NOT_REQUIRED' },
    notes: 'SNOOZE/DISMISS/NOT_RELEVANT. Governance is always fixed MATERIAL_FINANCIAL. Phase 3 review finding 4 delivery step 6 reclassification: PropertyTaxAppealCase is a workflow/status tracker (PREPARING -> FILED -> HEARING_SCHEDULED -> DETERMINED) — by the time this action surfaces, the homeowner already decided to appeal, so this is execution continuity, not a fresh material decision with a verdict to snapshot.',
  },
  {
    producerId: 'loadSavingsBenefitsActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'SavingsBenefitAction (prisma.savingsBenefitAction.findMany) + PropertyHiddenAssetMatch (prisma.propertyHiddenAssetMatch.findMany) — two id-prefixed sub-shapes.',
    sourceKind: 'SAVINGS_BENEFITS',
    idPrefixes: ['savings-benefit-action:', 'savings-benefit-match:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    decisionLineagePolicy: {
      kind: 'VARIES_BY_INSTANCE',
      rationale: 'Two id-prefixed sub-shapes sharing one fixed MATERIAL_FINANCIAL governance, but not the same decision-lineage need. "match" (savings-benefit-match:) is a fresh HIGH-confidence PropertyHiddenAssetMatch recommendation — savingsBenefitMatchDecisionFamilyAdapter (domainSnapshotAdapters.ts, Phase 3 review finding 4 delivery step 6) wraps it. "action" (savings-benefit-action:) is resuming an already-started SavingsBenefitAction — execution continuity, not a fresh decision, exempted to NOT_REQUIRED by prefix in resolveActionDecisionLineagePolicy (homeActionDecisionLineage.ts), same reasoning as OPERATIONAL_WORK_ID_PREFIX.',
    },
    notes: 'Two id-prefixed sub-shapes: "action" (SNOOZE/DEFER/DISMISS/NOT_RELEVANT) and "match" (ACKNOWLEDGE, DEFER, SNOOZE, DISMISS, NOT_RELEVANT, CORRECT_FACT). supportedCommands above is the union of both.',
  },
  {
    producerId: 'loadOwnershipCostChangeActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'OwnershipCostSnapshot (prisma.ownershipCostSnapshot.findFirst).',
    sourceKind: 'SYSTEM',
    idPrefixes: [OWNERSHIP_COST_CHANGE_ID_PREFIX],
    hasCompletionAdapter: true,
    completionAdapterOwner: 'ownershipCostDecisionService.record (services/ownershipCosts/ownershipCostDecision.service.ts), routed by id prefix in executeHomeActionCommand (homeActions.service.ts)',
    isKindLevelCompletionException: true,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['COMPLETE', 'DEFER', 'SNOOZE', 'DISMISS', 'ALREADY_DONE', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: 'ownershipCostDecisionService.record (services/ownershipCosts/ownershipCostDecision.service.ts), routed by OWNERSHIP_COST_CHANGE_ID_PREFIX in executeHomeActionCommand — owns every command for this producer, not completion only.',
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    decisionLineagePolicy: { kind: 'DECISION_REQUIRED', decisionDefinitionId: 'OWNERSHIP_COST_CHANGE' },
    notes: 'COMPLETE/ALREADY_DONE supported despite the SYSTEM source kind having no completion adapter at the kind level — this is one of the two id-prefix carve-outs executeHomeActionCommand checks explicitly (see OWNERSHIP_COST_CHANGE_ID_PREFIX above), now declared here instead of being an undeclared exception. Governance is always fixed MATERIAL_FINANCIAL; ownershipCostDecisionService.record already models RESOLVE/SNOOZE/NO_ACTION/DISMISS as a real decision. Phase 3 review finding 4 delivery step 6: ownershipCostChangeDecisionFamilyAdapter (domainSnapshotAdapters.ts) wraps the latest material OwnershipCostChange per (propertyId, category) — note the decision-lineage primaryEntityId is that composite key, not change.id, matching this producer\'s own lineageId identity. Home Intelligence FRD Phase 5 work item 2, rule 5 of 7 (HI-CMP-002): a MORTGAGE_PRINCIPAL/MORTGAGE_INTEREST change additionally checks for a ready refinance opportunity (getReadyMortgageRefinanceOpportunitySummary) and enriches evidence/CTA/priority when one exists — id/lineageId/decisionLineagePolicy are unaffected, so this stays the same obligation, never a competing action.',
  },
  {
    producerId: 'adaptOrchestratedActionToHomeAction',
    sourceFile: 'apps/backend/src/services/orchestration.service.ts',
    factSignalOrigin: 'Risk assessment engine output (orchestration.service.ts) — a pre-computed action object passed in by the caller, not a direct DB query inside this adapter; the underlying domain signal varies per orchestrated risk type.',
    sourceKind: null,
    idPrefixes: [],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    dynamicWorkItemOwnership: [
      { sourceKind: 'MAINTENANCE', workItemSourceType: 'MAINTENANCE' },
      { sourceKind: 'COVERAGE', workItemSourceType: 'COVERAGE' },
    ],
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    decisionLineagePolicy: {
      kind: 'VARIES_BY_INSTANCE',
      rationale: 'safetyTier is critical ? SAFETY_EMERGENCY : hasSavedCoverageAnalysis ? MATERIAL_FINANCIAL : LOW_CONSEQUENCE per action. The MATERIAL_FINANCIAL branch already has an authoritative underlying output (the saved Coverage Analysis) an adapter could snapshot -- a real future decision family, not a from-scratch engine -- but none is registered yet, so it fails closed today -- resolved per-action by resolveActionDecisionLineagePolicy.',
    },
    notes: 'Risk-assessment adapter. Computes source.kind per action (MAINTENANCE/COVERAGE/SYSTEM) from action.source/relatedEntity rather than emitting one fixed kind, and builds id from the raw action.actionKey with no producer prefix — the least identity-stable producer in the feed. ACKNOWLEDGE only.',
  },
  {
    producerId: 'getActivationFirstValue',
    sourceFile: 'apps/backend/src/services/entryContext.service.ts',
    factSignalOrigin: 'PropertyOnboarding.activeTriggerId, resolved by sourceAdapterForTrigger (entryContext.service.ts) to whichever domain record the trigger type points at (Incident/Warranty/InsurancePolicy/etc.).',
    sourceKind: null,
    idPrefixes: [ACTIVATION_ID_PREFIX],
    hasCompletionAdapter: true,
    completionAdapterOwner: 'recordFirstActionResolution (services/entryContext.service.ts), routed by id prefix in executeHomeActionCommand (homeActions.service.ts)',
    isKindLevelCompletionException: true,
    workKeyEligible: false,
    workItemSourceType: null,
    dynamicWorkItemOwnership: [
      { sourceKind: 'MAINTENANCE', workItemSourceType: 'MAINTENANCE' },
      { sourceKind: 'COVERAGE', workItemSourceType: 'COVERAGE' },
      { sourceKind: 'INCIDENT', workItemSourceType: 'INCIDENT' },
      { sourceKind: 'PROJECT', workItemSourceType: 'PROJECT' },
      { sourceKind: 'GUIDANCE', workItemSourceType: 'GUIDANCE' },
    ],
    supportedCommands: ['COMPLETE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: 'recordFirstActionResolution (services/entryContext.service.ts), routed by ACTIVATION_ID_PREFIX in executeHomeActionCommand — applies only to the "activation:" id family. The "activation-context:" family this producer also emits (see notes) falls through to the generic default and has no COMPLETE control, so it never reaches this owner.',
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    decisionLineagePolicy: {
      kind: 'VARIES_BY_INSTANCE',
      rationale: 'Resolves to whatever the pointed-at domain record\'s own governance is (Incident/Warranty/InsurancePolicy/etc. via sourceAdapterForTrigger), so tier varies. This producer\'s job is driving first engagement, not itself computing a fresh material recommendation -- resolved per-action by resolveActionDecisionLineagePolicy like every other dynamic producer, so a genuinely material first-value trigger still fails closed rather than being silently exempted.',
    },
    notes: 'Activation/first-value producer. source.kind is resolved dynamically per trigger type by sourceAdapterForTrigger (entryContext.service.ts) — can be MAINTENANCE, COVERAGE, INCIDENT, PROJECT, SYSTEM, or GUIDANCE. This is the other id-prefix carve-out executeHomeActionCommand checks explicitly (see ACTIVATION_ID_PREFIX above), now declared here instead of being an undeclared exception. isKindLevelCompletionException is still meaningful here even though sourceKind is null: whichever dynamic kind is resolved at runtime, none of them declare a kind-level completion adapter, so the exception always applies. This producer also emits a second, separate id family — "activation-context:${triggerId}" — for the missing-facts follow-up action. That family is NOT covered by idPrefixes above and intentionally has no COMPLETE control: recordFirstActionResolution is scoped to the single "activation:" trigger action and would misrecord firstActionResolvedAt if invoked for it. It self-resolves by dropping out of the feed once its `missing` list is empty. supportedCommands above is the "activation:" family only; the "activation-context:" family supports DEFER/DISMISS/NOT_RELEVANT/CORRECT_FACT.',
  },
  {
    producerId: 'appendAcceptedOperationalWork',
    sourceFile: 'apps/backend/src/services/homeActions.service.ts',
    factSignalOrigin: 'OperationalWorkItem (prisma.operationalWorkItem.findMany, acceptanceState: ACCEPTED).',
    sourceKind: null,
    idPrefixes: [OPERATIONAL_WORK_ID_PREFIX],
    hasCompletionAdapter: true,
    completionAdapterOwner: 'completeAcceptedOperationalWorkItem (services/homeActionCompletion.service.ts), routed by OPERATIONAL_WORK_ID_PREFIX in executeHomeActionCommand — maintenance-execution items only (Phase 4 slice 1); other execution types keep no COMPLETE control this pass.',
    isKindLevelCompletionException: true,
    workKeyEligible: false,
    workItemSourceType: null,
    carriesExistingWorkItem: true,
    supportedCommands: ['CORRECT_FACT', 'SNOOZE', 'COMPLETE', 'ALREADY_DONE'],
    commandOwner: 'completeAcceptedOperationalWorkItem (services/homeActionCompletion.service.ts) for COMPLETE/ALREADY_DONE on a maintenance-backed item; generic default otherwise.',
    hasOutcomeAdapter: true,
    outcomeAdapterOwner: 'recordOperationalWorkOutcome (services/decisionPlatform/outcomeObservationService.ts) — OPERATIONAL_WORK_ITEM source type, created by completeAcceptedOperationalWorkItem.',
    decisionLineagePolicy: { kind: 'NOT_REQUIRED' },
    notes: 'Re-projects already-ACCEPTED OperationalWorkItem rows back into the feed with source.kind computed from the item\'s primary execution type (PROJECT/GUIDANCE/MAINTENANCE). Never routes through proposeWorkItemFromHomeAction — it already carries an existing work item reference, so workKeyEligible is not applicable rather than a real "no." Home Intelligence FRD Phase 4: COMPLETE/ALREADY_DONE is offered only when the primary execution is MAINTENANCE_TASK and the item\'s safetyTier completion-evidence policy permits attestation (LOW_CONSEQUENCE/MATERIAL_FINANCIAL) — REGULATED_COVERAGE/SAFETY_EMERGENCY items keep CORRECT_FACT/SNOOZE only, same as GUIDANCE/PROJECT-backed items, and must use "Manage action" instead. Phase 3 review finding 4: exempted from decision lineage even when material — this is execution continuity on already-accepted work, not fresh decision creation (the decision, if any, already happened when the work was accepted); resolveActionDecisionLineagePolicy explicitly exempts the OPERATIONAL_WORK_ID_PREFIX id family for this reason.',
  },
] as const;
