import type { HomeActionProducerOwnershipEntry } from './homeActionProducerOwnership.contract';

/**
 * Home Intelligence Functional Completeness FRD §15 Phase 0 work item 2 —
 * inventory of every function that produces Home Actions, confirmed by
 * direct code read of homeActionSourcePromotion.service.ts's
 * getPromotedHomeActions() call list, orchestration.service.ts's risk
 * assessment adapter, entryContext.service.ts's activation adapter, and
 * homeActions.service.ts's already-accepted-work re-projection.
 *
 * HomeAction carries no stable producerId field — only source.kind (11
 * values, shared by several distinct producers) and source.entityId (the
 * domain entity's own id, not a producer tag). Some, not all, producers
 * build action.id with a fixed literal prefix; executeHomeActionCommand
 * already exploits two of those prefixes (see OWNERSHIP_COST_CHANGE_ID_PREFIX
 * / ACTIVATION_ID_PREFIX below) to route completion commands past the
 * source-kind-level SOURCE_KINDS_WITHOUT_COMPLETION_ADAPTER guard in
 * homeActionAdapterOwnership.ts. Because no producer identifier is
 * available on the action object itself, this registry is necessarily
 * static/declarative (keyed by loader function name) rather than derived
 * from a live HomeAction — a per-loader schema field is a larger change
 * than Phase 0 scope (see this file's sibling completeness test,
 * homeActionProducerOwnership.test.js, which is what actually catches a
 * new loader added without a row here).
 *
 * commandOwner note: unless stated otherwise, "generic default" below means
 * executeHomeActionCommand's fallback path (homeActions.service.ts) —
 * snoozeAction for DEFER/SNOOZE, recordOrchestrationEvent for every other
 * command — which runs for every producer that has no producer-specific
 * branch. Every workKeyEligible producer additionally gets the shared
 * snoozeWorkItem/transitionWorkItem side effects applied against
 * action.workItem before whichever commandOwner below runs; that shared
 * step is declared once here rather than repeated in every entry.
 */

export const OWNERSHIP_COST_CHANGE_ID_PREFIX = 'ownership-cost-change:';
export const ACTIVATION_ID_PREFIX = 'activation:';

const GENERIC_DEFAULT_COMMAND_OWNER = 'Generic default (executeHomeActionCommand, services/homeActions.service.ts): snoozeAction for DEFER/SNOOZE, recordOrchestrationEvent otherwise.';

export const HOME_ACTION_PRODUCER_OWNERSHIP: readonly HomeActionProducerOwnershipEntry[] = [
  {
    producerId: 'adaptEnvironmentInsightsToHomeActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'EnvironmentInsight[] — passed in by the caller (already-fetched weather/environment API results), not a direct DB query inside this adapter.',
    sourceKind: 'MAINTENANCE',
    idPrefixes: ['environment:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: true,
    workItemSourceType: 'MAINTENANCE',
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    notes: 'ACKNOWLEDGE only.',
  },
  {
    producerId: 'loadGuidanceActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'ProjectRecord + GuidanceJourney (prisma.projectRecord.findMany with its guidance journey/step include).',
    sourceKind: 'GUIDANCE',
    idPrefixes: [],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: true,
    workItemSourceType: 'GUIDANCE',
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    notes: 'ACKNOWLEDGE only. No fixed id prefix.',
  },
  {
    producerId: 'loadIncidentActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'Incident (prisma.incident.findMany).',
    sourceKind: 'INCIDENT',
    idPrefixes: ['incident:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: true,
    workItemSourceType: 'INCIDENT',
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    notes: 'ACKNOWLEDGE, plus CORRECT_FACT when critical (critical incidents restrict feedbackControls to [\'ACKNOWLEDGE\', \'CORRECT_FACT\'], a subset of the full set shown here).',
  },
  {
    producerId: 'loadSeasonalChecklistActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'SeasonalChecklist (prisma.seasonalChecklist.findMany).',
    sourceKind: 'MAINTENANCE',
    idPrefixes: ['seasonal-checklist:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['SNOOZE', 'NOT_RELEVANT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    notes: 'One aggregate action over many checklist items — mapping it to a single work item would be semantically wrong, so it is explicitly excluded from work-item eligibility (isSeasonalAggregate in homeActionWorkItem.adapter.ts) even though the MAINTENANCE kind is otherwise eligible. SNOOZE/NOT_RELEVANT only.',
  },
  {
    producerId: 'loadRecallActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'RecallMatch (prisma.recallMatch.findMany).',
    sourceKind: 'RECALL',
    idPrefixes: ['recall:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: true,
    workItemSourceType: 'RECALL',
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    notes: 'ACKNOWLEDGE, plus CORRECT_FACT when critical (same subset relationship as loadIncidentActions).',
  },
  {
    producerId: 'loadInspectionFindingActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'InspectionFinding (prisma.inspectionFinding.findMany).',
    sourceKind: 'INSPECTION_FINDING',
    idPrefixes: ['inspection-finding:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    notes: 'ACKNOWLEDGE, plus CORRECT_FACT when safety-relevant (same subset relationship as loadIncidentActions). Not yet promoted into a work item — later-phase work.',
  },
  {
    producerId: 'loadCoverageActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'CoverageReview (prisma.coverageReview.findMany).',
    sourceKind: 'COVERAGE',
    idPrefixes: [],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: true,
    workItemSourceType: 'COVERAGE',
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    notes: 'ACKNOWLEDGE only. No fixed id prefix.',
  },
  {
    producerId: 'loadCoverageRenewalActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'Warranty + InsurancePolicy (prisma.warranty.findMany, prisma.insurancePolicy.findMany).',
    sourceKind: 'COVERAGE',
    idPrefixes: ['coverage-renewal:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: true,
    workItemSourceType: 'COVERAGE',
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    notes: 'ACKNOWLEDGE only. Added Phase 1 Slice 1 (Warranty/InsurancePolicy renewal) — the producer this Phase 0 pass adds a row for after it was missing from the original registry report.',
  },
  {
    producerId: 'loadHealthInsightActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'Property + InventoryItem + Warranty (prisma.property.findUnique with inventoryItems/warranties include) — a computed health score, not one single domain record.',
    sourceKind: 'SYSTEM',
    idPrefixes: ['health-insight:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    notes: 'ACKNOWLEDGE only. Added Phase 1 Slice 2 (health-score/appliance install-year gaps) — the producer this Phase 0 pass adds a row for after it was missing from the original registry report.',
  },
  {
    producerId: 'loadRepairReplaceDecisionActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'ReplaceRepairAnalysis (prisma.replaceRepairAnalysis.findMany).',
    sourceKind: 'GUIDANCE',
    idPrefixes: ['repair-replace:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: true,
    workItemSourceType: 'GUIDANCE',
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    notes: 'ACKNOWLEDGE only. Added Phase 1 Slice 2 (ReplaceRepairAnalysis) — the producer this Phase 0 pass adds a row for after it was missing from the original registry report.',
  },
  {
    producerId: 'loadPersonalizationActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'PersonalizedRecommendation (prisma.personalizedRecommendation.findMany).',
    sourceKind: 'PERSONALIZATION',
    idPrefixes: ['personalization:'],
    hasCompletionAdapter: true,
    completionAdapterOwner: 'applyPersonalizationHomeActionLifecycle (modules/personalization/application/applyHomeActionLifecycle.usecase.ts)',
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['COMPLETE', 'DEFER', 'SNOOZE', 'DISMISS', 'ALREADY_DONE', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: 'applyPersonalizationHomeActionLifecycle (modules/personalization/application/applyHomeActionLifecycle.usecase.ts), routed by source.kind === PERSONALIZATION in executeHomeActionCommand.',
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    notes: 'The only producer with a real COMPLETE/ALREADY_DONE adapter declared at the source-kind level too — no id-prefix carve-out needed. (Safety-tier recommendations restrict feedbackControls to [\'COMPLETE\', \'ALREADY_DONE\', \'CORRECT_FACT\'], a subset of the full set shown here.)',
  },
  {
    producerId: 'loadProjectActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'ProjectRecord (prisma.projectRecord.findMany).',
    sourceKind: 'PROJECT',
    idPrefixes: ['project:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: true,
    workItemSourceType: 'PROJECT',
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    notes: 'ACKNOWLEDGE only.',
  },
  {
    producerId: 'loadSalePrepActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'PropertySaleCase (prisma.propertySaleCase.findUnique).',
    sourceKind: 'SALE_PREP',
    idPrefixes: [],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: true,
    workItemSourceType: 'SALE_PREP',
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    notes: 'Completion happens by the homeowner updating the self-reported condition on Sale Case, not a COMPLETE command against the promoted work item. Id is per-item with an "industry-guidance" suffix, not one fixed literal prefix.',
  },
  {
    producerId: 'loadRefinanceDataRequiredActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'DomainEvent (prisma.domainEvent.findFirst).',
    sourceKind: 'SYSTEM',
    idPrefixes: ['refinance-data-required:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'NO_MORTGAGE', 'CORRECT_FACT'],
    commandOwner: 'markPropertyAsHavingNoMortgage (services/homeActions.service.ts) for the exact-id NO_MORTGAGE command only, by exact string match (not an id-prefix check) in executeHomeActionCommand; every other command falls through to the generic default.',
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    notes: 'ACKNOWLEDGE, plus a NO_MORTGAGE command handled directly by exact-id match in executeHomeActionCommand (markPropertyAsHavingNoMortgage). Note: NO_MORTGAGE does not short-circuit — the generic default handler still runs afterward for this command too.',
  },
  {
    producerId: 'loadRefinanceOpportunityActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'PropertyRefinanceRadarState (prisma.propertyRefinanceRadarState.findUnique).',
    sourceKind: 'SYSTEM',
    idPrefixes: [],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    notes: 'ACKNOWLEDGE only. Id scheme varies per case (refinance-decision-review or a window id) rather than one fixed prefix.',
  },
  {
    producerId: 'loadHomeDigitalTwinFactReviewActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'HomeDigitalTwin (prisma.homeDigitalTwin.findUnique).',
    sourceKind: 'SYSTEM',
    idPrefixes: ['home-digital-twin-fact-review:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['DISMISS', 'SNOOZE', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    notes: 'DISMISS/SNOOZE/NOT_RELEVANT/CORRECT_FACT.',
  },
  {
    producerId: 'loadHomeCapitalTimelineMaterialWindowActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'HomeCapitalTimelineAnalysis (prisma.homeCapitalTimelineAnalysis.findFirst).',
    sourceKind: 'SYSTEM',
    idPrefixes: [],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['DISMISS', 'SNOOZE', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    notes: 'DISMISS/SNOOZE/NOT_RELEVANT/CORRECT_FACT. Own id scheme keyed off recommendationVersion, not a fixed literal prefix.',
  },
  {
    producerId: 'loadPropertyTaxAppealCaseActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'PropertyTaxAppealCase (prisma.propertyTaxAppealCase.findFirst).',
    sourceKind: 'SYSTEM',
    idPrefixes: ['property-tax-appeal-case:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['SNOOZE', 'DISMISS', 'NOT_RELEVANT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    notes: 'SNOOZE/DISMISS/NOT_RELEVANT.',
  },
  {
    producerId: 'loadSavingsBenefitsActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'SavingsBenefitAction (prisma.savingsBenefitAction.findMany) + PropertyHiddenAssetMatch (prisma.propertyHiddenAssetMatch.findMany) — two id-prefixed sub-shapes.',
    sourceKind: 'SAVINGS_BENEFITS',
    idPrefixes: ['savings-benefit-action:', 'savings-benefit-match:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    notes: 'Two id-prefixed sub-shapes: "action" (SNOOZE/DEFER/DISMISS/NOT_RELEVANT) and "match" (ACKNOWLEDGE, DEFER, SNOOZE, DISMISS, NOT_RELEVANT, CORRECT_FACT). supportedCommands above is the union of both.',
  },
  {
    producerId: 'loadOwnershipCostChangeActions',
    sourceFile: 'apps/backend/src/services/homeActionSourcePromotion.service.ts',
    factSignalOrigin: 'OwnershipCostSnapshot (prisma.ownershipCostSnapshot.findFirst).',
    sourceKind: 'SYSTEM',
    idPrefixes: [OWNERSHIP_COST_CHANGE_ID_PREFIX],
    hasCompletionAdapter: true,
    completionAdapterOwner: 'ownershipCostDecisionService.record (services/ownershipCosts/ownershipCostDecision.service.ts), routed by id prefix in executeHomeActionCommand (homeActions.service.ts)',
    isKindLevelCompletionException: true,
    workKeyEligible: false,
    workItemSourceType: null,
    supportedCommands: ['COMPLETE', 'DEFER', 'SNOOZE', 'DISMISS', 'ALREADY_DONE', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: 'ownershipCostDecisionService.record (services/ownershipCosts/ownershipCostDecision.service.ts), routed by OWNERSHIP_COST_CHANGE_ID_PREFIX in executeHomeActionCommand — owns every command for this producer, not completion only.',
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    notes: 'COMPLETE/ALREADY_DONE supported despite the SYSTEM source kind having no completion adapter at the kind level — this is one of the two id-prefix carve-outs executeHomeActionCommand checks explicitly (see OWNERSHIP_COST_CHANGE_ID_PREFIX above), now declared here instead of being an undeclared exception.',
  },
  {
    producerId: 'adaptOrchestratedActionToHomeAction',
    sourceFile: 'apps/backend/src/services/orchestration.service.ts',
    factSignalOrigin: 'Risk assessment engine output (orchestration.service.ts) — a pre-computed action object passed in by the caller, not a direct DB query inside this adapter; the underlying domain signal varies per orchestrated risk type.',
    sourceKind: null,
    idPrefixes: [],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    dynamicWorkItemOwnership: [
      { sourceKind: 'MAINTENANCE', workItemSourceType: 'MAINTENANCE' },
      { sourceKind: 'COVERAGE', workItemSourceType: 'COVERAGE' },
    ],
    supportedCommands: ['ACKNOWLEDGE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    notes: 'Risk-assessment adapter. Computes source.kind per action (MAINTENANCE/COVERAGE/SYSTEM) from action.source/relatedEntity rather than emitting one fixed kind, and builds id from the raw action.actionKey with no producer prefix — the least identity-stable producer in the feed. ACKNOWLEDGE only.',
  },
  {
    producerId: 'getActivationFirstValue',
    sourceFile: 'apps/backend/src/services/entryContext.service.ts',
    factSignalOrigin: 'PropertyOnboarding.activeTriggerId, resolved by sourceAdapterForTrigger (entryContext.service.ts) to whichever domain record the trigger type points at (Incident/Warranty/InsurancePolicy/etc.).',
    sourceKind: null,
    idPrefixes: [ACTIVATION_ID_PREFIX],
    hasCompletionAdapter: true,
    completionAdapterOwner: 'recordFirstActionResolution (services/entryContext.service.ts), routed by id prefix in executeHomeActionCommand (homeActions.service.ts)',
    isKindLevelCompletionException: true,
    workKeyEligible: false,
    workItemSourceType: null,
    dynamicWorkItemOwnership: [
      { sourceKind: 'MAINTENANCE', workItemSourceType: 'MAINTENANCE' },
      { sourceKind: 'COVERAGE', workItemSourceType: 'COVERAGE' },
      { sourceKind: 'INCIDENT', workItemSourceType: 'INCIDENT' },
      { sourceKind: 'PROJECT', workItemSourceType: 'PROJECT' },
      { sourceKind: 'GUIDANCE', workItemSourceType: 'GUIDANCE' },
    ],
    supportedCommands: ['COMPLETE', 'DEFER', 'SNOOZE', 'DISMISS', 'NOT_RELEVANT', 'CORRECT_FACT'],
    commandOwner: 'recordFirstActionResolution (services/entryContext.service.ts), routed by ACTIVATION_ID_PREFIX in executeHomeActionCommand — applies only to the "activation:" id family. The "activation-context:" family this producer also emits (see notes) falls through to the generic default and has no COMPLETE control, so it never reaches this owner.',
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    notes: 'Activation/first-value producer. source.kind is resolved dynamically per trigger type by sourceAdapterForTrigger (entryContext.service.ts) — can be MAINTENANCE, COVERAGE, INCIDENT, PROJECT, SYSTEM, or GUIDANCE. This is the other id-prefix carve-out executeHomeActionCommand checks explicitly (see ACTIVATION_ID_PREFIX above), now declared here instead of being an undeclared exception. isKindLevelCompletionException is still meaningful here even though sourceKind is null: whichever dynamic kind is resolved at runtime, none of them declare a kind-level completion adapter, so the exception always applies. This producer also emits a second, separate id family — "activation-context:${triggerId}" — for the missing-facts follow-up action. That family is NOT covered by idPrefixes above and intentionally has no COMPLETE control: recordFirstActionResolution is scoped to the single "activation:" trigger action and would misrecord firstActionResolvedAt if invoked for it. It self-resolves by dropping out of the feed once its `missing` list is empty. supportedCommands above is the "activation:" family only; the "activation-context:" family supports DEFER/DISMISS/NOT_RELEVANT/CORRECT_FACT.',
  },
  {
    producerId: 'appendAcceptedOperationalWork',
    sourceFile: 'apps/backend/src/services/homeActions.service.ts',
    factSignalOrigin: 'OperationalWorkItem (prisma.operationalWorkItem.findMany, acceptanceState: ACCEPTED).',
    sourceKind: null,
    idPrefixes: ['operational-work:'],
    hasCompletionAdapter: false,
    completionAdapterOwner: null,
    isKindLevelCompletionException: false,
    workKeyEligible: false,
    workItemSourceType: null,
    carriesExistingWorkItem: true,
    supportedCommands: ['CORRECT_FACT', 'SNOOZE'],
    commandOwner: GENERIC_DEFAULT_COMMAND_OWNER,
    hasOutcomeAdapter: false,
    outcomeAdapterOwner: null,
    notes: 'Re-projects already-ACCEPTED OperationalWorkItem rows back into the feed with source.kind computed from the item\'s primary execution type (PROJECT/GUIDANCE/MAINTENANCE). Never routes through proposeWorkItemFromHomeAction — it already carries an existing work item reference, so workKeyEligible is not applicable rather than a real "no."',
  },
] as const;
