export enum SellerPrepEvent {
    CHECKLIST_VIEWED = 'SELLER_PREP_CHECKLIST_VIEWED',
    ITEM_MARKED_DONE = 'SELLER_PREP_ITEM_DONE',
    LEAD_CREATED = 'SELLER_PREP_LEAD_CREATED',
    REPORT_VIEWED = 'SELLER_PREP_REPORT_VIEWED',
  }
  