apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-stack
  namespace: argocd # This app lives in the argocd namespace
spec:
  project: default
  source:
    repoURL: https://github.com/madhuboyin/contract-to-cozy1.git # Or your repo URL
    targetRevision: HEAD
    path: infrastructure/kubernetes/overlays/raspberry-pi # POINTER 1: Kustomize path
  destination:
    server: https://kubernetes.default.svc
    # POINTER 2: Deploy to the 'contract-to-cozy' namespace
    namespace: contract-to-cozy 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true # Automatically create the namespace if it's missing
