import { DECIDE_COMPARE_CAPABILITIES } from './decideCompare';
import { MAINTAIN_PREVENT_CAPABILITIES } from './maintainPrevent';
import { PLAN_BUDGET_CAPABILITIES } from './planBudget';
import { PROTECT_MONITOR_CAPABILITIES } from './protectMonitor';
import { SAVE_OPTIMIZE_CAPABILITIES } from './saveOptimize';
import { UNDERSTAND_HOME_CAPABILITIES } from './understandHome';

export {
  DECIDE_COMPARE_CAPABILITIES,
  MAINTAIN_PREVENT_CAPABILITIES,
  PLAN_BUDGET_CAPABILITIES,
  PROTECT_MONITOR_CAPABILITIES,
  SAVE_OPTIMIZE_CAPABILITIES,
  UNDERSTAND_HOME_CAPABILITIES,
};

export const ALL_TOOL_CAPABILITY_DEFINITIONS = [
  ...UNDERSTAND_HOME_CAPABILITIES,
  ...MAINTAIN_PREVENT_CAPABILITIES,
  ...PROTECT_MONITOR_CAPABILITIES,
  ...DECIDE_COMPARE_CAPABILITIES,
  ...PLAN_BUDGET_CAPABILITIES,
  ...SAVE_OPTIMIZE_CAPABILITIES,
] as const;
