import { buildCapabilityDefinitions } from './capabilityDefinitionFactory';

export const MAINTAIN_PREVENT_CAPABILITIES = buildCapabilityDefinitions([
  {
    id: 'home-operations',
    label: 'Home Operations',
    description: 'Coordinate recommended, scheduled, active, and completed work without tracking the same obligation twice.',
    routeTemplate: '/dashboard/properties/[id]/home-operations',
    routeAliases: ['/dashboard/properties/[id]/action-plan'],
    outcomeCategory: 'MAINTAIN_PREVENT',
    rolloutKey: 'HOME_OPERATIONS',
    releaseStage: 'ACTIVE',
    safetyTier: 'LOW_CONSEQUENCE',
    completionKind: 'OUTCOME_VERIFIED',
    mode: 'CATALOG_ONLY',
    acceptedContext: ['PROPERTY', 'HOME_ACTION', 'WORK_ITEM', 'FINDING', 'PROJECT', 'JOURNEY'],
    livingHomeRecordReads: ['operational-work-item', 'maintenance-task', 'guidance-journey', 'inspection-finding', 'project-record'],
    livingHomeRecordWrites: ['operational-work-event', 'operational-work-evidence', 'home-event'],
    expectedOutput: 'One durable, governed work portfolio with source, execution, evidence, and outcome lineage.',
    completionSignal: 'operational_work_outcome_verified',
    outputEntityTypes: ['WORK_ITEM'],
  },
  {
    id: 'maintenance',
    label: 'Maintenance',
    description: 'Execute atomic, recurring, seasonal, and adopted routine work.',
    routeTemplate: '/dashboard/maintenance',
    outcomeCategory: 'MAINTAIN_PREVENT',
    rolloutKey: 'MAINTENANCE',
    releaseStage: 'ACTIVE',
    safetyTier: 'LOW_CONSEQUENCE',
    completionKind: 'ACTION_COMPLETED',
    mode: 'CATALOG_ONLY',
    acceptedContext: ['PROPERTY', 'HOME_ACTION', 'WORK_ITEM', 'INVENTORY_ITEM', 'FINDING'],
    livingHomeRecordReads: ['property-context', 'maintenance-task', 'seasonal-checklist-item', 'property-habit'],
    livingHomeRecordWrites: ['maintenance-task', 'operational-work-item', 'home-event'],
    expectedOutput: 'An atomic or recurring task whose completion updates the canonical home record.',
    completionSignal: 'maintenance_task_completed',
    outputEntityTypes: ['WORK_ITEM'],
  },
  {
    id: 'home-habit-coach',
    label: 'Home Habit Coach',
    description: 'Build seasonal routines that keep home care on track.',
    routeTemplate: '/dashboard/properties/[id]/tools/home-habit-coach',
    outcomeCategory: 'MAINTAIN_PREVENT',
    rolloutKey: 'HOME_HABIT_COACH',
    releaseStage: 'ACTIVE',
    safetyTier: 'LOW_CONSEQUENCE',
    completionKind: 'ACTION_INITIATED',
    mode: 'CONTEXTUAL',
  },
  {
    id: 'plant-advisor',
    version: 2,
    label: 'Plant Advisor',
    description: 'Choose plants using room light and maintenance context.',
    routeTemplate: '/dashboard/properties/[id]/tools/plant-advisor',
    outcomeCategory: 'MAINTAIN_PREVENT',
    rolloutKey: 'PLANT_ADVISOR',
    releaseStage: 'ACTIVE',
    safetyTier: 'LOW_CONSEQUENCE',
    completionKind: 'OUTPUT_GENERATED',
    mode: 'CONTEXTUAL',
    iconName: 'leaf',
    intentAliases: [
      'plant advisor',
      'what plant works in this room',
      'plants for low light',
      'pet safe houseplants',
      'easy care indoor plants',
      'room plant recommendations',
      'plant care plan',
    ],
    homeownerOutcome:
      'Choose reviewed plants that fit a specific room, its light, care preference, and household constraints.',
    livingHomeRecordReads: [
      'property-context',
      'room-record',
      'room-plant-profile',
      'home-plant',
    ],
    livingHomeRecordWrites: [
      'room-plant-profile',
      'plant-recommendation',
      'home-plant',
      'plant-care-plan',
    ],
    expectedOutput:
      'A reviewed, room-specific plant recommendation set with fit reasons, warnings, placement, and care guidance.',
    completionSignal: 'plant_recommendations_generated',
    outputEntityTypes: ['ROOM'],
  },
]);
