import { buildCapabilityDefinitions } from './capabilityDefinitionFactory';

export const PLAN_BUDGET_CAPABILITIES = buildCapabilityDefinitions(([
  ['budget', 'Budget Planner', 'Plan and track home spending.', '/dashboard/budget', 'BUDGET_PLANNER', 'BETA', 'LOW_CONSEQUENCE', 'CATALOG_ONLY'],
  ['capital-timeline', 'Home Capital Timeline', 'Plan major home system and capital events.', '/dashboard/properties/[id]/tools/capital-timeline', 'HOME_CAPITAL_TIMELINE', 'ACTIVE', 'MATERIAL_FINANCIAL', 'CONTEXTUAL'],
  ['diy', 'DIY Project Center', 'Use reviewed guidance for eligible low-risk projects.', '/dashboard/properties/[id]/tools/diy', 'DIY', 'ACTIVE', 'LOW_CONSEQUENCE', 'CONTEXTUAL'],
  ['documents', 'Document Vault', 'Organize and review critical home documents.', '/dashboard/documents', 'DOCUMENT_VAULT', 'BETA', 'LOW_CONSEQUENCE', 'CATALOG_ONLY'],
  ['emergency', 'Emergency Help', 'Access rapid guidance for urgent home incidents.', '/dashboard/emergency', 'EMERGENCY_HELP', 'BETA', 'SAFETY_EMERGENCY', 'CATALOG_ONLY'],
  ['hoa-compliance', 'HOA Compliance', 'Track HOA approvals and compliance requirements.', '/dashboard/properties/[id]/tools/hoa', 'HOA_COMPLIANCE', 'ACTIVE', 'LOW_CONSEQUENCE', 'CONTEXTUAL'],
  ['home-renovation-risk-advisor', 'Renovation Risk Advisor', 'Review rules and execution risks before major upgrades.', '/dashboard/properties/[id]/tools/home-renovation-risk-advisor', 'RENOVATION_RISK_ADVISOR', 'ACTIVE', 'LOW_CONSEQUENCE', 'CONTEXTUAL'],
  ['home-timeline', 'Home Timeline', 'Review major events and plans across home ownership.', '/dashboard/properties/[id]/timeline', 'HOME_TIMELINE', 'ACTIVE', 'LOW_CONSEQUENCE', 'CATALOG_ONLY'],
  ['inspection-hub', 'Inspection Hub', 'Organize inspection reports and track open findings.', '/dashboard/properties/[id]/inspection-hub', 'INSPECTION_HUB', 'ACTIVE', 'LOW_CONSEQUENCE', 'CONTEXTUAL'],
  ['modifications', 'Home Upgrades', 'Plan improvements and review their expected impact.', '/dashboard/modifications', 'HOME_UPGRADES', 'BETA', 'LOW_CONSEQUENCE', 'CATALOG_ONLY'],
  ['oracle', 'Appliance Oracle', 'Review appliance lifespan and replacement timing.', '/dashboard/oracle', 'APPLIANCE_ORACLE', 'ACTIVE', 'LOW_CONSEQUENCE', 'CATALOG_ONLY'],
  ['permits', 'Permit Tracker', 'Track permits, inspections, and disclosure records.', '/dashboard/properties/[id]/tools/permits', 'PERMITS', 'ACTIVE', 'LOW_CONSEQUENCE', 'CONTEXTUAL'],
  ['project-tracker', 'Project Tracker', 'Track contractor projects from contract to completion.', '/dashboard/properties/[id]/projects', 'PROJECT_TRACKER', 'ACTIVE', 'LOW_CONSEQUENCE', 'CONTEXTUAL'],
  ['reserve-fund', 'Reserve Fund Planner', 'Plan reserves for future repairs and replacements.', '/dashboard/properties/[id]/tools/reserve-fund', 'RESERVE_FUND', 'ACTIVE', 'MATERIAL_FINANCIAL', 'CATALOG_ONLY'],
  ['seller-prep', 'Seller Prep', 'Prepare the property, documents, and timeline for sale.', '/dashboard/properties/[id]/seller-prep', 'SELLER_PREP', 'ACTIVE', 'LOW_CONSEQUENCE', 'CONTEXTUAL'],
  ['status-board', 'Status Board', 'Review readiness and active priorities in one place.', '/dashboard/properties/[id]/status-board', 'STATUS_BOARD', 'ACTIVE', 'LOW_CONSEQUENCE', 'CONTEXTUAL'],
  ['tax-appeal', 'Tax Appeals', 'Evaluate and prepare a property tax appeal.', '/dashboard/tax-appeal', 'TAX_APPEAL', 'ACTIVE', 'LOW_CONSEQUENCE', 'CATALOG_ONLY'],
] as const).map(([
  id,
  label,
  description,
  routeTemplate,
  rolloutKey,
  releaseStage,
  safetyTier,
  mode,
]) => ({
  id,
  label,
  description,
  routeTemplate,
  outcomeCategory: 'PLAN_BUDGET' as const,
  rolloutKey,
  releaseStage,
  safetyTier,
  completionKind: 'PLAN_CREATED' as const,
  mode,
})));
