import { buildCapabilityDefinitions } from './capabilityDefinitionFactory';

export const UNDERSTAND_HOME_CAPABILITIES = buildCapabilityDefinitions([
  {
    id: 'home-digital-will',
    version: 2,
    label: 'Home Digital Will',
    description: 'Prepare critical home knowledge for trusted parties.',
    routeTemplate: '/dashboard/properties/[id]/tools/home-digital-will',
    outcomeCategory: 'UNDERSTAND_HOME',
    rolloutKey: 'HOME_DIGITAL_WILL',
    releaseStage: 'ACTIVE',
    safetyTier: 'LOW_CONSEQUENCE',
    completionKind: 'ARTIFACT_CREATED',
    mode: 'CONTEXTUAL',
    iconName: 'file-check',
    intentAliases: [
      'home digital will',
      'prepare home information for an emergency',
      'trusted contact home access',
      'critical home documents handoff',
      'what someone needs to manage my home',
      'property knowledge transfer',
      'home emergency instructions',
    ],
    homeownerOutcome:
      'Publish a governed property handoff that gives trusted people only the home knowledge they are authorized to receive.',
    livingHomeRecordReads: [
      'property-context',
      'critical-property-document',
      'trusted-contact-readiness',
      'emergency-instruction',
    ],
    livingHomeRecordWrites: [
      'governed-home-handoff',
      'trusted-contact-access-policy',
    ],
    expectedOutput:
      'A validated, access-scoped Home Digital Will handoff artifact for trusted property continuity.',
    completionSignal: 'home_digital_will_published',
    outputEntityTypes: ['DOCUMENT'],
  },
  {
    id: 'home-risk-replay',
    label: 'Home Risk Replay',
    description: 'Review the events and risks this home has experienced.',
    routeTemplate: '/dashboard/properties/[id]/tools/home-risk-replay',
    outcomeCategory: 'UNDERSTAND_HOME',
    rolloutKey: 'HOME_RISK_REPLAY',
    releaseStage: 'ACTIVE',
    safetyTier: 'LOW_CONSEQUENCE',
    completionKind: 'OUTPUT_VIEWED',
    mode: 'CONTEXTUAL',
    iconName: 'shield-alert',
  },
  {
    id: 'material-specs',
    version: 2,
    label: 'Material Specs',
    description: 'Record finishes, products, colors, and supplier details.',
    routeTemplate: '/dashboard/properties/[id]/materials',
    outcomeCategory: 'UNDERSTAND_HOME',
    rolloutKey: 'MATERIAL_SPECS',
    releaseStage: 'ACTIVE',
    safetyTier: 'LOW_CONSEQUENCE',
    completionKind: 'ARTIFACT_CREATED',
    mode: 'CONTEXTUAL',
    iconName: 'layers',
    intentAliases: [
      'material specs',
      'what paint did i use',
      'find my paint color',
      'match a repair finish',
      'room finishes',
      'tile flooring and product details',
      'material document',
    ],
    homeownerOutcome:
      'Keep a reusable record of the exact finishes and products used in each room or project.',
    livingHomeRecordReads: [
      'property-context',
      'project-record',
      'room-record',
    ],
    livingHomeRecordWrites: ['material-specification'],
    expectedOutput:
      'A durable material specification linked to its property, room, or project context.',
    completionSignal: 'material_specification_saved',
    outputEntityTypes: ['DOCUMENT'],
  },
]);
