import { GuidanceJourneyTemplate } from './guidanceTypes';

const templates: GuidanceJourneyTemplate[] = [
  {
    journeyTypeKey: 'asset_lifecycle_resolution',
    journeyKey: 'journey_asset_lifecycle_resolution',
    signalIntentFamilies: ['lifecycle_end_or_past_life', 'maintenance_failure_risk'],
    issueDomain: 'ASSET_LIFECYCLE',
    defaultDecisionStage: 'DIAGNOSIS',
    defaultReadiness: 'NEEDS_CONTEXT',
    canonicalFirstStepKey: 'repair_replace_decision',
    steps: [
      {
        stepOrder: 1,
        stepKey: 'repair_replace_decision',
        stepType: 'DECISION',
        label: 'Decide repair vs replace',
        description: 'Use existing repair and failure context to choose a durable path.',
        decisionStage: 'DECISION',
        executionReadiness: 'NEEDS_CONTEXT',
        isRequired: true,
        toolKey: 'replace-repair',
        flowKey: 'replace-repair-analysis',
        routePath: '/dashboard/properties/:propertyId/inventory/items/:itemId/replace-repair',
      },
      {
        stepOrder: 2,
        stepKey: 'check_coverage',
        stepType: 'VALIDATION',
        label: 'Check coverage and deductible exposure',
        description: 'Verify policy and warranty overlap before executing spend.',
        decisionStage: 'VALIDATION',
        executionReadiness: 'NEEDS_CONTEXT',
        isRequired: true,
        toolKey: 'coverage-intelligence',
        flowKey: 'coverage-analysis',
        routePath: '/dashboard/properties/:propertyId/tools/coverage-intelligence',
      },
      {
        stepOrder: 3,
        stepKey: 'validate_price',
        stepType: 'VALIDATION',
        label: 'Validate fair market price',
        decisionStage: 'VALIDATION',
        executionReadiness: 'NEEDS_CONTEXT',
        isRequired: true,
        toolKey: 'service-price-radar',
        flowKey: 'service-price-radar',
        routePath: '/dashboard/properties/:propertyId/tools/service-price-radar',
      },
      {
        stepOrder: 4,
        stepKey: 'prepare_negotiation',
        stepType: 'VALIDATION',
        label: 'Prepare negotiation strategy',
        decisionStage: 'VALIDATION',
        executionReadiness: 'NEEDS_CONTEXT',
        isRequired: false,
        toolKey: 'negotiation-shield',
        flowKey: 'negotiation-shield',
        routePath: '/dashboard/properties/:propertyId/tools/negotiation-shield',
      },
      {
        stepOrder: 5,
        stepKey: 'book_service',
        stepType: 'EXECUTION',
        label: 'Book service execution',
        decisionStage: 'EXECUTION',
        executionReadiness: 'READY',
        isRequired: true,
        toolKey: 'booking',
        flowKey: 'booking',
        routePath: '/dashboard/bookings',
      },
    ],
  },
  {
    journeyTypeKey: 'coverage_gap_resolution',
    journeyKey: 'journey_coverage_gap_resolution',
    signalIntentFamilies: ['coverage_gap', 'coverage_lapse_detected'],
    issueDomain: 'INSURANCE',
    defaultDecisionStage: 'AWARENESS',
    defaultReadiness: 'NEEDS_CONTEXT',
    canonicalFirstStepKey: 'check_coverage',
    steps: [
      {
        stepOrder: 1,
        stepKey: 'check_coverage',
        stepType: 'DIAGNOSIS',
        label: 'Review current coverage',
        decisionStage: 'DIAGNOSIS',
        executionReadiness: 'NEEDS_CONTEXT',
        isRequired: true,
        toolKey: 'coverage-intelligence',
        flowKey: 'coverage-analysis',
        routePath: '/dashboard/properties/:propertyId/tools/coverage-intelligence',
      },
      {
        stepOrder: 2,
        stepKey: 'estimate_exposure',
        stepType: 'DECISION',
        label: 'Estimate uncovered exposure',
        decisionStage: 'DECISION',
        executionReadiness: 'NEEDS_CONTEXT',
        isRequired: true,
        toolKey: 'true-cost',
        flowKey: 'true-cost-ownership',
        routePath: '/dashboard/properties/:propertyId/tools/true-cost',
      },
      {
        stepOrder: 3,
        stepKey: 'compare_coverage_options',
        stepType: 'DECISION',
        label: 'Compare policy and warranty options',
        decisionStage: 'DECISION',
        executionReadiness: 'NEEDS_CONTEXT',
        isRequired: true,
        toolKey: 'insurance-trend',
        flowKey: 'insurance-cost-trend',
        routePath: '/dashboard/properties/:propertyId/tools/insurance-trend',
      },
      {
        stepOrder: 4,
        stepKey: 'update_policy_or_documents',
        stepType: 'EXECUTION',
        label: 'Update policy or upload documents',
        decisionStage: 'EXECUTION',
        executionReadiness: 'READY',
        isRequired: true,
        toolKey: 'documents',
        flowKey: 'vault',
        routePath: '/dashboard/vault',
      },
    ],
  },
  {
    journeyTypeKey: 'recall_safety_resolution',
    journeyKey: 'journey_recall_safety_resolution',
    signalIntentFamilies: ['recall_detected'],
    issueDomain: 'SAFETY',
    defaultDecisionStage: 'AWARENESS',
    defaultReadiness: 'READY',
    canonicalFirstStepKey: 'safety_alert',
    steps: [
      {
        stepOrder: 1,
        stepKey: 'safety_alert',
        stepType: 'AWARENESS',
        label: 'Acknowledge safety alert',
        decisionStage: 'AWARENESS',
        executionReadiness: 'READY',
        isRequired: true,
        toolKey: 'recalls',
        flowKey: 'recall-alert',
        routePath: '/dashboard/properties/:propertyId/tools/home-event-radar',
      },
      {
        stepOrder: 2,
        stepKey: 'review_remedy_instructions',
        stepType: 'DIAGNOSIS',
        label: 'Review remedy instructions',
        decisionStage: 'DIAGNOSIS',
        executionReadiness: 'READY',
        isRequired: true,
        toolKey: 'recalls',
        flowKey: 'recall-remedy',
      },
      {
        stepOrder: 3,
        stepKey: 'recall_resolution',
        stepType: 'EXECUTION',
        label: 'Confirm recall outcome',
        decisionStage: 'EXECUTION',
        executionReadiness: 'READY',
        isRequired: true,
        toolKey: 'recalls',
        flowKey: 'recall-resolution',
      },
    ],
  },
  {
    journeyTypeKey: 'inspection_followup_resolution',
    journeyKey: 'journey_inspection_followup_resolution',
    signalIntentFamilies: ['inspection_followup_needed'],
    issueDomain: 'MAINTENANCE',
    defaultDecisionStage: 'DIAGNOSIS',
    defaultReadiness: 'NEEDS_CONTEXT',
    canonicalFirstStepKey: 'assess_urgency',
    steps: [
      {
        stepOrder: 1,
        stepKey: 'assess_urgency',
        stepType: 'DIAGNOSIS',
        label: 'Assess urgency from inspection findings',
        decisionStage: 'DIAGNOSIS',
        executionReadiness: 'NEEDS_CONTEXT',
        isRequired: true,
        toolKey: 'inspection-report',
        flowKey: 'inspection-report-analysis',
        routePath: '/dashboard/inspection-report',
      },
      {
        stepOrder: 2,
        stepKey: 'estimate_repair_cost',
        stepType: 'DECISION',
        label: 'Estimate repair scope and cost',
        decisionStage: 'DECISION',
        executionReadiness: 'NEEDS_CONTEXT',
        isRequired: true,
        toolKey: 'service-price-radar',
        flowKey: 'service-price-radar',
      },
      {
        stepOrder: 3,
        stepKey: 'route_specialist',
        stepType: 'EXECUTION',
        label: 'Route to specialist and schedule',
        decisionStage: 'EXECUTION',
        executionReadiness: 'READY',
        isRequired: true,
        toolKey: 'booking',
        flowKey: 'booking',
        routePath: '/dashboard/bookings',
      },
      {
        stepOrder: 4,
        stepKey: 'track_resolution',
        stepType: 'TRACKING',
        label: 'Track resolution completion',
        decisionStage: 'TRACKING',
        executionReadiness: 'TRACKING_ONLY',
        isRequired: true,
        toolKey: 'home-event-radar',
        flowKey: 'home-event-radar',
      },
    ],
  },
  {
    journeyTypeKey: 'financial_exposure_resolution',
    journeyKey: 'journey_financial_exposure_resolution',
    signalIntentFamilies: ['financial_exposure', 'cost_of_inaction_risk'],
    issueDomain: 'FINANCIAL',
    defaultDecisionStage: 'DIAGNOSIS',
    defaultReadiness: 'NEEDS_CONTEXT',
    canonicalFirstStepKey: 'estimate_out_of_pocket_cost',
    steps: [
      {
        stepOrder: 1,
        stepKey: 'estimate_out_of_pocket_cost',
        stepType: 'DIAGNOSIS',
        label: 'Estimate out-of-pocket cost',
        decisionStage: 'DIAGNOSIS',
        executionReadiness: 'NEEDS_CONTEXT',
        isRequired: true,
        toolKey: 'true-cost',
        flowKey: 'true-cost-ownership',
      },
      {
        stepOrder: 2,
        stepKey: 'compare_action_options',
        stepType: 'DECISION',
        label: 'Compare action vs delay',
        decisionStage: 'DECISION',
        executionReadiness: 'NEEDS_CONTEXT',
        isRequired: true,
        toolKey: 'do-nothing-simulator',
        flowKey: 'do-nothing-simulator',
      },
      {
        stepOrder: 3,
        stepKey: 'evaluate_savings_funding',
        stepType: 'DECISION',
        label: 'Evaluate savings and funding options',
        decisionStage: 'DECISION',
        executionReadiness: 'NEEDS_CONTEXT',
        isRequired: true,
        toolKey: 'home-savings',
        flowKey: 'home-savings',
      },
      {
        stepOrder: 4,
        stepKey: 'route_financial_plan',
        stepType: 'TRACKING',
        label: 'Route to capital plan timeline',
        decisionStage: 'TRACKING',
        executionReadiness: 'TRACKING_ONLY',
        isRequired: false,
        toolKey: 'capital-timeline',
        flowKey: 'home-capital-timeline',
      },
    ],
  },
];

const templateByFamily = new Map<string, GuidanceJourneyTemplate>();
for (const template of templates) {
  for (const family of template.signalIntentFamilies) {
    templateByFamily.set(family, template);
  }
}

export const DEFAULT_TEMPLATE: GuidanceJourneyTemplate = {
  journeyTypeKey: 'generic_guidance_resolution',
  journeyKey: 'journey_generic_guidance_resolution',
  signalIntentFamilies: ['generic_actionable_signal'],
  issueDomain: 'OTHER',
  defaultDecisionStage: 'AWARENESS',
  defaultReadiness: 'UNKNOWN',
  canonicalFirstStepKey: 'review_signal',
  steps: [
    {
      stepOrder: 1,
      stepKey: 'review_signal',
      stepType: 'AWARENESS',
      label: 'Review guidance signal',
      decisionStage: 'AWARENESS',
      executionReadiness: 'UNKNOWN',
      isRequired: true,
      toolKey: 'home-event-radar',
      flowKey: 'home-event-radar',
    },
  ],
};

export const TOOL_DEFAULT_STEP_KEY: Record<string, string> = {
  'replace-repair': 'repair_replace_decision',
  'coverage-intelligence': 'check_coverage',
  recalls: 'recall_resolution',
  booking: 'book_service',
  'inspection-report': 'assess_urgency',
  'service-price-radar': 'validate_price',
  'negotiation-shield': 'prepare_negotiation',
  'do-nothing-simulator': 'compare_action_options',
  'home-savings': 'evaluate_savings_funding',
};

export function getGuidanceTemplateBySignalFamily(signalIntentFamily?: string | null): GuidanceJourneyTemplate {
  if (!signalIntentFamily) return DEFAULT_TEMPLATE;
  return templateByFamily.get(signalIntentFamily) ?? DEFAULT_TEMPLATE;
}

export function listGuidanceTemplates(): GuidanceJourneyTemplate[] {
  return templates;
}
